- README.md
- Updates to the root README file, mainly adding example of batched & strided API
> Editing README file to add strided batched API

- clients/gtest/blas1_gtest.cpp
- clients/gtest/gemm_gtest.cpp
- clients/include/testing_gemm.hpp
- library/src/blas3/Tensile/Tensile_status.cpp
- library/src/blas3/Tensile/gemm.cpp
- library/src/handle.cpp
- library/src/rocblas_auxiliary.cpp
- library/src/status.cpp
resolves #___
-  optimize gemm testing case 
-  fix the bug which does not report find solution as a failure in gemm test case
-  add argument checker in gemm. cpp (check ldx and matrix size)
-  unify the indentation as 4 spaces everywhere
> fix bugs in gemm test and unify the indentation

- clients/gtest/blas1_gtest.cpp
- library/src/handle.cpp
- library/src/rocblas_auxiliary.cpp
resolves #___
-  add more blas1 routine test
> add more blas1 test cases

- clients/benchmarks/CMakeLists.txt
- fix the bug introduced in Kent's last pull request (refactoring cmakefile)   
-  
-
> fix the bug in benchmarking building

- CMakeLists.txt
- clients/CMakeLists.txt
- clients/benchmarks/client.cpp
- library/CMakeLists.txt
- library/src/blas3/Tensile/gemm.cpp
resolves #___
-  other minors: typo, building.
-
> fix a serious bug in gemm.cpp : mixing number of rows & columns

- clients/CMakeLists.txt
- clients/cmake/external-lapack.cmake
- library/src/blas3/Tensile/gemm.cpp
- library/src/include/definitions.h
> add more macro to detect errors; add debug info in gemm.cpp

- library/src/blas3/Tensile/gemm.cpp
> add more debug info in gemm.cpp

- library/src/blas3/Tensile/gemm.cpp
> add required headers

- clients/benchmarks/client.cpp
- clients/common/cblas_interface.cpp
- clients/gtest/CMakeLists.txt
- clients/gtest/ger_gtest.cpp
- clients/include/cblas_interface.h
- clients/include/flops.h
- clients/include/testing_ger.hpp
- library/include/rocblas.hpp
- library/include/rocblas_functions.h
- library/src/CMakeLists.txt
- library/src/blas2/ger_device.h
- library/src/blas2/rocblas_ger.cpp
-  add rocblas_sger and rocblas_dger to rocBLAS library
-  small changes to make existing gemv tests run
> add [SD]GER kernel, test, and benchmark

- clients/gtest/gemm_gtest.cpp
- clients/include/testing_gemm.hpp
resolves #___
-  add to gemm unit tests problem sizes m,n,k = 3, 3, 3   and    m,n,k = 5, 5, 5
-  These sizes are giving errors
-
> error found for gemm with dimensions 3, 3, 3 and 5, 5, 5

- clients/common/cblas_interface.cpp
- clients/gtest/gemm_gtest.cpp
- clients/include/cblas_interface.h
- clients/include/testing_gemm.hpp
- clients/include/testing_trsm.hpp
- library/src/blas3/rocblas_trsm.cpp
- library/src/blas3/trtri_device.h
- library/src/blas3/trtri_trsm.hpp
resolves #___
-  now the trsm works for even bigger size 
-  improve the numerical stability by generating a good conditioned matrix in trsm 
-  remove an invalid case in gemm test to prevent abort 
-  add trmm cblas interface
> fix the bug in trsm 

- clients/benchmarks/client.cpp
- library/include/rocblas_types.h
resolves #___
-  in rocblas_types.h make enum rocblas_status_ members have consecutive integer values
-  in clients.cpp add back evaluation of lda, ldb, ldc
-
> fix typo in rocblas_types and bug in client

- Jenkinsfile
- clients/benchmarks/client.cpp
- clients/common/cblas_interface.cpp
- clients/common/unit.cpp
- clients/gtest/trsm_gtest.cpp
- clients/include/cblas_interface.h
- clients/include/testing_gemm.hpp
- clients/include/testing_trsm.hpp
- clients/include/testing_trtri.hpp
- clients/include/unit.h
- clients/include/utility.h
- library/src/blas3/rocblas_trsm.cpp
- library/src/blas3/trtri_device.h
resolves #___
-  factorize the matrix A with LU factorization first and then serve to trsm
-  add LU (getrf) interface
> generate good conditioning matrix

- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Ailk_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Ailk_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Ailk_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Ailk_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Alik_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Alik_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Alik_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Alik_Bljk_SB.yaml
> newer faster Tensile config files for Fiji ROCm 1.4

- Jenkinsfile
-  Depending on release or debug builds, test executables
may have an executable name post-fix.  Make the name 
post-fix a variable.
> Fix variable executable post-fix naming

- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Ailk_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Ailk_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Ailk_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Ailk_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Alik_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Alik_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Alik_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm14/Fiji_Cijk_Alik_Bljk_SB.yaml
> updating Tensile yaml files to work with Tensile v2.2 recursive logic

- cmake/external-Tensile.cmake
resolves #___
-  pull Tensile from RadeonOpenCompute not guacamoleo
-  
-
> change Tensile from guacamoleo to RadeonOpenCompute

- cmake/external-Tensile.cmake
> Download Tensile from tag v2.2.0 rather than from a branch

- cmake/build-version.cmake
> version for Pre-release

- Jenkinsfile
- cmake/external-Tensile.cmake
- library/src/blas3/Tensile/Logic/FijiROCm15/Fiji_Cijk_Ailk_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm15/Fiji_Cijk_Ailk_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm15/Fiji_Cijk_Ailk_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm15/Fiji_Cijk_Ailk_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm15/Fiji_Cijk_Alik_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm15/Fiji_Cijk_Alik_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm15/Fiji_Cijk_Alik_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/FijiROCm15/Fiji_Cijk_Alik_Bljk_SB.yaml
> upgrading to Tensile 2.4.5

- library/src/blas3/trtri.hpp
> protect reading out of boundary in trtri gemm

- clients/common/utility.cpp
resolves #___
-   register info does not show correctly but only 0 , so replace it with grid info
-   
-
> add max grid info

- README.md
update documentation, no code change
> adding rules for obtaining rocBLAS from Legacy BLAS

- clients/gtest/CMakeLists.txt
- clients/gtest/set_get_pointer_mode_gtest.cpp
- library/include/rocblas-auxiliary.h
- library/include/rocblas-types.h
- library/src/blas1/rocblas_amax.cpp
- library/src/blas1/rocblas_amin.cpp
- library/src/blas1/rocblas_asum.cpp
- library/src/blas1/rocblas_axpy.cpp
- library/src/blas1/rocblas_dot.cpp
- library/src/blas1/rocblas_nrm2.cpp
- library/src/blas1/rocblas_scal.cpp
- library/src/blas2/rocblas_gemv.cpp
- library/src/blas2/rocblas_ger.cpp
- library/src/include/handle.h
- library/src/rocblas_auxiliary.cpp
- Add variable rocblas_pointer_mode to handle
- Add functions rocblas_set_pointer_mode and rocblas_get_pointer_mode
- Change enum name rocblas_mem_location to rocblas_pointer_mode
> Set get pointer mode

- .github/CONTRIBUTING.md
> add Contributor License Agreement

- clients/CMakeLists.txt
- clients/cmake/external-boost.cmake
- clients/common/utility.cpp
> update boost to 1.63 tested by clang 3.8 and above

- README.md
- clients/gtest/blas1_gtest.cpp
- clients/include/testing_amax.hpp
- clients/include/testing_asum.hpp
- clients/include/testing_axpy.hpp
- clients/include/testing_copy.hpp
- clients/include/testing_dot.hpp
- clients/include/testing_nrm2.hpp
- clients/include/testing_scal.hpp
- clients/include/testing_swap.hpp
- library/src/blas1/rocblas_amax.cpp
- library/src/blas1/rocblas_amin.cpp
- library/src/blas1/rocblas_asum.cpp
- library/src/blas1/rocblas_axpy.cpp
- library/src/blas1/rocblas_copy.cpp
- library/src/blas1/rocblas_dot.cpp
- library/src/blas1/rocblas_nrm2.cpp
- library/src/blas1/rocblas_scal.cpp
- library/src/blas1/rocblas_swap.cpp
Add level 1 and ger functionality for argument inc < 1. Add argument checking for inc arguments.
Update Readme.md to fix link and remove text on rocBLAS running on CUDA.
> Inc arg check

- clients/common/arg_check.cpp
- clients/gtest/blas1_gtest.cpp
- clients/gtest/ger_gtest.cpp
- clients/include/testing_amax.hpp
- clients/include/testing_asum.hpp
- clients/include/testing_axpy.hpp
- clients/include/testing_copy.hpp
- clients/include/testing_dot.hpp
- clients/include/testing_ger.hpp
- clients/include/testing_nrm2.hpp
- clients/include/testing_scal.hpp
- clients/include/testing_swap.hpp
- library/src/blas1/rocblas_amax.cpp
- library/src/blas1/rocblas_asum.cpp
- library/src/blas2/ger_device.h
- library/src/blas2/rocblas_ger.cpp
add tests to BLAS1 to check error returns where pointer args are nullptr
> add tests to BLAS1 for nullptr

- clients/common/arg_check.cpp
- clients/gtest/gemv_gtest.cpp
- clients/gtest/ger_gtest.cpp
- clients/include/arg_check.h
- clients/include/testing_amax.hpp
- clients/include/testing_asum.hpp
- clients/include/testing_axpy.hpp
- clients/include/testing_bandwidth.hpp
- clients/include/testing_copy.hpp
- clients/include/testing_dot.hpp
- clients/include/testing_gemm.hpp
- clients/include/testing_gemm_strided_batched.hpp
- clients/include/testing_gemv.hpp
- clients/include/testing_ger.hpp
- clients/include/testing_nrm2.hpp
- clients/include/testing_scal.hpp
- clients/include/testing_set_get_matrix.hpp
- clients/include/testing_set_get_vector.hpp
- clients/include/testing_swap.hpp
- clients/include/testing_symv.hpp
- clients/include/testing_trmm.hpp
- clients/include/testing_trsm.hpp
- clients/include/testing_trtri.hpp
- clients/include/testing_trtri_batched.hpp
- library/src/blas2/gemv_device.h
- library/src/blas2/ger_device.h
- library/src/blas2/rocblas_gemv.cpp
modify function gemv to allow for inc < 0. With this modification gemv is compliant with the reference implementation.
Refactor tests
> add inc < 0 for gemv + refactoring tests

- clients/common/cblas_interface.cpp
- clients/common/norm.cpp
- clients/common/unit.cpp
- clients/gtest/trsm_gtest.cpp
- clients/include/cblas_interface.h
- clients/include/testing_trsm.hpp
- clients/include/unit.h
resolves # swdev-12710
- initialize with L from Cholesky factorization of SPD matrix
-  test error and residual using reference trmm in place of reference trsm
-
> improve trsm tests

- clients/samples/CMakeLists.txt
- clients/samples/example_sgemm.cpp
- clients/samples/example_sgemm_strided_batched.cpp
add sample code for both sgemm and sgemm_strided_batched
> add samples for sgemm and sgemm_strided_batched

- clients/benchmarks/client.cpp
- clients/include/flops.h
- clients/include/testing_axpy.hpp
- clients/include/testing_dot.hpp
- clients/include/testing_scal.hpp
add benchmark for axpy, and gflop calculation for dot and scal
> add benchmarks for axpy, dot, scal

- clients/samples/example_sscal.cpp
> add pass message to example_sscal

- Jenkinsfile
- docker/dockerfile-build-hip-hcc-ctu-ubuntu-16.04
- docker/dockerfile-build-rocm-terminal
- install.sh
- library/CMakeLists.txt
- library/src/CMakeLists.txt
-  Added ability for install.sh to run as root without sudo
-  Adding rpm builds (built in Ubuntu though)
-  Removing library suffixes, giving cuda builds different package names
> install.sh w/o sudo, packaging work

- clients/benchmarks/perf_script/README.txt
- clients/benchmarks/perf_script/blasPerformanceTesting.py
update executable name: client -> rocblas-bench
add dependency information to README
> perf_script updates

- clients/gtest/gemm_strided_batched_gtest.cpp
> add tests for rocblas_dgemm_strided_batched

- clients/common/arg_check.cpp
- clients/include/arg_check.h
- clients/include/testing_geam.hpp
- library/src/blas3/geam_device.h
- library/src/blas3/rocblas_geam.cpp
inplace geam is for   C <- alpha * A + beta * B   for the two special cases:
1.     C <- alpha * C + beta * B
requires C == A, lda == ldc, transA == 'N'
2.     C <- alpha * A + beta * C
requires C == B, ldb == ldc, transB == 'N'
> add inplace geam

- clients/benchmarks/client.cpp
- clients/common/arg_check.cpp
- clients/common/cblas_interface.cpp
- clients/common/rocblas_template_specialization.cpp
- clients/gtest/blas1_gtest.cpp
- clients/include/arg_check.h
- clients/include/cblas_interface.h
- clients/include/rocblas.hpp
- clients/include/testing_iamax.hpp
- library/include/rocblas-functions.h
- library/src/blas1/rocblas_amax.cpp
- library/src/blas1/rocblas_amin.cpp
Correct API with change
rocblas_samax -> rocblas_isamax
rocblas_damax -> rocblas_idamax
> change api amax -> iamax

- clients/include/testing_gemm.hpp
> remove extra string   norm-error

- clients/include/testing_iamax.hpp
- library/src/blas1/rocblas_amax.cpp
BLAS uses Fortran one based indexing, not C Language zero based indexing.
Correct iXamax to use one based indexing.
> correct iXamax to 1 based index, not 0 based index

- clients/gtest/gemm_gtest.cpp
add gemm test for matrix size m,n,k < 4
> add gemm test m=n=k=1,2,3

- clients/gtest/gemm_gtest.cpp
> disable gemm tests for m<4

- clients/common/arg_check.cpp
- clients/gtest/blas1_gtest.cpp
- clients/gtest/geam_gtest.cpp
- clients/gtest/gemv_gtest.cpp
- clients/include/arg_check.h
- clients/include/rocblas_test_unique_ptr.hpp
- clients/include/testing_asum.hpp
- clients/include/testing_axpy.hpp
- clients/include/testing_copy.hpp
- clients/include/testing_dot.hpp
- clients/include/testing_geam.hpp
- clients/include/testing_gemv.hpp
- clients/include/testing_ger.hpp
- clients/include/testing_iamax.hpp
- clients/include/testing_nrm2.hpp
- clients/include/testing_scal.hpp
- clients/include/testing_swap.hpp
- clients/include/utility.h
refactor tests
* use std::unique_ptr for hipMalloc and hipFree
* use std::unique_ptr for rocblas_create_handle and rocblas_destroy_handle
* all tests for rocblas_pointer_mode_host and rocblas_pointer_mode_device
> use unique_ptr and test both pointer modes

- CMakeLists.txt
> making deepbench tuning the default

- clients/benchmarks/client.cpp
- clients/common/arg_check.cpp
- clients/gtest/set_get_matrix_gtest.cpp
- clients/gtest/set_get_vector_gtest.cpp
- clients/include/arg_check.h
- clients/include/testing_set_get_matrix.hpp
- clients/include/testing_set_get_vector.hpp
- clients/include/utility.h
> refactor set/get vector/matrix for host/dev ptr mode

- CMakeLists.txt
> add NO_GIT_TAG_VERSION go remove sha in build name

- clients/include/testing_asum.hpp
- clients/include/testing_geam.hpp
- library/src/blas1/rocblas_asum.cpp
- library/src/blas3/rocblas_geam.cpp
> use device->pointer_mode in geam asum

- CMakeLists.txt
> to use Tensile v3.3.7 with v_add_i32->u32 fix for gfx803

- library/src/include/definitions.h
> __global__ to __device__ for rocblas_fmadd_half2

- CMakeLists.txt
- clients/cmake/build-options.cmake
- install.sh
- library/CMakeLists.txt
-  Packaging fix for /opt/rocm
-  BUILD_WITH_TENSILE works for clients too
-
> Fixing packaging install path

- Jenkinsfile
If hcc_ctu tests fail it will be good to have them report UNSTABLE not FAILURE. This allows the pull request to pass, but it will be colored yellow to indicate the hcc_ctu failure.
> change hcc_ctu currentBuild.result from FAILURE to UNSTABLE

- library/include/rocblas-version.h.in
additional space prevented version string being substituted
> fix rocblas-version.h.in

- clients/benchmarks/CMakeLists.txt
- clients/gtest/CMakeLists.txt
- clients/samples/CMakeLists.txt
- install.sh
-  Primarily refactoring of the install.sh script to build on centos/rhel & fedora
> CentOS & RHEL & Fedora install logic

- library/src/blas1/rocblas_amax.cpp
- library/src/blas1/rocblas_amin.cpp
- library/src/blas1/rocblas_asum.cpp
- library/src/blas1/rocblas_axpy.cpp
- library/src/blas1/rocblas_copy.cpp
- library/src/blas1/rocblas_dot.cpp
- library/src/blas1/rocblas_nrm2.cpp
- library/src/blas1/rocblas_scal.cpp
- library/src/blas1/rocblas_swap.cpp
- library/src/blas2/rocblas_gemv.cpp
- library/src/blas2/rocblas_ger.cpp
- library/src/blas3/rocblas_geam.cpp
- library/src/blas3/rocblas_trmm.cpp
- library/src/blas3/trtri.hpp
- library/src/blas3/trtri_batched.hpp
- library/src/blas3/trtri_trsm.hpp
- library/src/rocblas_auxiliary.cpp
Change from using hipLaunchKernel to use hipLaunchKernelGGL.
> hipLaunchKernelGGL replaces hipLaunchKernel

- CMakeLists.txt
> pull Tensile 3.5.1 with race condition fix

- CMakeLists.txt
> Add status log to fix download error for tensil

- Jenkinsfile
Currently Jenkinsfile only builds for hcc_ctu. Add back build for rocm_ubuntu.
> add back rocm_ubuntu to Jenkinsfile

- install.sh
Fixes CMake error in finding dependencies.
> fix install dir for dependencies

- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_SB.yaml
Resolves error:
AttributeError: 'KernelWriterAssembly' objecet has no attribute 'startSgprAddressA'
> Change BufferLoad to true in vega10_Cijk_Alik_Bljk_SB.yaml

- Jenkinsfile
> change Jenkins timeout to 2hr

- library/src/blas3/rocblas_trsm.cpp
> solve weired string in trsm.cpp

- Jenkinsfile
Set up Jenkinsfile to run nightly tests at 3 AM. Used same code as MIOpen and Tensile.
Pre-checkin tests work as they did before. Currently, _all_ tests are performed, so the next step is to overhaul tests with labels "checkin" and "nightly", and uncomment these filters in the Jenkinsfile.
> add nightly infrastructure to Jenkinsfile

- clients/gtest/blas1_gtest.cpp
- library/src/blas1/rocblas_asum.cpp
- library/src/blas1/rocblas_dot.cpp
- library/src/blas1/rocblas_nrm2.cpp
The reason is  the index error in the second reduction kernel 
-  
-  
-
> fix the bug in blas1 when size is > 1024*1024

- Jenkinsfile
change from running on specific machines jenkins-rocm-0 and jenkins-rocm-0 to any gfx900 machine.
> test rocm_ubuntu on jenkins-rocm-3

- library/src/blas3/Tensile/Logic/asm_full/vega10_Cij_Aik_Bkj_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_SB.yaml
new vega10*S*yaml files from Tensile for tuning with DataInitTypeBeta : 0. This trains Tensile for beta==0 rather than beta!=0.
> new vega10 yaml files for DataInitTypeBeta : 0

- clients/include/testing_gemm_strided_batched.hpp
> fix calculated us (micro seconds)

- Jenkinsfile
previously ctu tests hung on a call to /opt/rocm/bin/rocm_agent_enumerator.  Add back ctu testing to see if the hang is still present.
> try adding back ctu testing

- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_SB.yaml
.yaml files from new Tensile training
> merge ResNet Exact into one Benchmark Group

- install.sh
> add RHEL 7 support

- library/src/blas1/device_template.h
add useful information that has been removed from the wiki
> add information from wiki

- clients/gtest/set_get_matrix_gtest.cpp
- clients/include/testing_set_get_matrix.hpp
- clients/include/utility.h
- library/src/rocblas_auxiliary.cpp
All other tests use M and N for number of rows and cols. Change the set-get_matrix tests to also use M and N.
> change set_get_matrix_gtest to use M,N in place of row,col

- clients/include/testing_gemm.hpp
use size_t in place of int for malloc sizes in testing_gemm.hp
> use size_t for malloc sizes in testing_gemm.hpp

- library/src/blas3/rocblas_trsm.cpp
> workaround for large size ldb fail in trsm

- library/src/blas3/rocblas_trsm.cpp
> format fix

- .github/CONTRIBUTING.md
Add information on clang-format and how to format files to CONTRIBUTING.md
> add clang-format info to CONTRIBUTING.md

- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_SB.yaml
dgemm_asm_lite w/Buffer{Load,Store}=0; sgemm_asm_full w/Buffer{Load,Store}=1
-  Generated logic using dgemm_asm_lite yaml file with Buffer{Load,Store}=0
-  Generated logic using sgemm_asm_full yaml file with Buffer{Load,Store}=1
> dgemm_asm_lite w/Buffer{Load,Store}=0; sgemm_asm_full w/Buffer{Load,Store}=1

- CMakeLists.txt
> version bumped to 0.13.2.3

- library/src/blas3/rocblas_trsm.cpp
> fixing large ldb bug in trsm copy

- Jenkinsfile
- clients/gtest/gemm_strided_batched_gtest.cpp
Add tests for known bug. Error occurs when stride_a = 0,  and k < 256. Note that tests do pass for k = 32, but not for 31 or 33.
> known_bug rocblas-test for stride_a = 0

- clients/samples/example_sgemm_strided_batched.cpp
print strided batched matrices
> print strided_batched

- library/src/blas3/Tensile/gemm.cpp
- library/src/blas3/rocblas_trsm.cpp
- library/src/blas3/trtri_device.h
- library/src/blas3/trtri_trsm.hpp
- library/src/handle.cpp
- library/src/include/handle.h
> Integrate TRSM improvements in develop

- CMakeLists.txt
- library/src/blas3/trtri_trsm.hpp
> trtri speed improvement with 2-stage recursion

- clients/gtest/gemm_gtest.cpp
- library/src/blas3/Tensile/gemm.cpp
Add chunking for BLAS dimension m to prevent the offset form exceeding the capacity of a 32 bit register. Previous pull requests #281 #289 are for chunking BLAS in the n dimension.
Also add tests for m and n chunking.
> add m chunking so offset fits in 32 bit register

- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bljk_HB.yaml
for hgemm hip 
- set VW=1 when ((m == 1) || (n == 1) || (k == 1))
- else set VW=2
With this change rocBLAS - hgemm - hip  tests pass.
> hgemm hip yaml update for VW=2 and VW=1

- library/src/CMakeLists.txt
> Use hip_device target

- CMakeLists.txt
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bljk_HB.yaml
retrained hgemm hip_lite YAML file using Tensile commit fcc8a7
> retrained hgemm hip_lite YAML file using Tensile commit fcc8a7

- .github/CONTRIBUTING.md
- README.md
Update README.md and CONTRIBUTING.md and fix broken links.
> updates to README.md and CONTRIBUTING.md

- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_HB.yaml
-  hgemm asm_full YAML update asserting psem=2 and pf0em=2 for Vega 10 assembly kernels
-  retrained hgemm hip_lite YAML file using Tensile commit fcc8a7
With this PR, many known_bugs cases are resolved.
> update hgemm asm_full YAML file for performance; re-train hgemm hip_lite YAML file

- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_HB.yaml
changes from Tensile PR#297 (from amcamd) for Vega 10
> changes from Tensile PR#297 for Vega 10

- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_HB.yaml
Changes to solution selection logic to call
hip kernels with VW=1 if m==1||n==1||k==1
hip kernels with VW=2 if m<=32||n<=32||k<=32
These changes are from Tensile PR#297
> changes from Tensile PR#297

- clients/gtest/gemm_gtest.cpp
hgemm known_bugs have been fixed, so change the test prefix known_bugs to checkin.
> change known_bug tests to checkin

- Jenkinsfile
move clang-format before tests for earlier notification of trivial clang-format errors
> move clang-format before test

- library/src/blas1/rocblas_axpy.cpp
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_DB.yaml
- library/src/blas3/Tensile/gemm.cpp
- library/src/include/definitions.h
-  __fp16->_Float16
-  disable PreciseBoundsCheck in Vega 10 dgemm asm_lite for all assembly kernels
> __fp16->_Float16; disable PreciseBoundsCheck in Vega 10 dgemm asm_lite

- library/src/blas1/rocblas_axpy.cpp
- library/src/blas3/Tensile/gemm.cpp
- library/src/include/definitions.h
> __fp16->_Float16

- library/src/blas3/trtri_batched.hpp
- library/src/include/definitions.h
Synch with develop branch:
-  Add \_\_device\_\_ to llvm_fma_v2f16
-  Add missing const qualifier for argument of trtri_kernel_batched
>  Add __device__ to llvm_fma_v2f16; add missing const qualifier for argument of trtri_kernel_batched

- clients/include/testing_gemm.hpp
- clients/include/testing_gemm_strided_batched.hpp
Check return codes from rocblas, run format tool
> Check return code

- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_HB.yaml
-  disable PreciseBoundsCheck for all Vega 10 HB YAML files
> disable PreciseBoundsCheck for all Vega 10 HB YAML files

- clients/gtest/gemm_gtest.cpp
- clients/gtest/gemm_strided_batched_gtest.cpp
Adding deepbench sizes to rocBLAS daily tests
> add deepbench gemm_strided_batched tests

- clients/gtest/gemm_ex_gtest.cpp
- clients/include/testing_gemm_ex.hpp
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_HBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_HBH.yaml
- library/src/blas_ex/rocblas_gemm_ex.cpp
Simplified YAML files pass tests for non-multiple of 8. There are still "known-bug" tests for m = 1.
Add tests for bad arguments and for chunking.
> additional gemm_ex tests, new YAML files

- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bljk_HB.yaml
re-trained HGEMM hip_lite and asm_full to match Tensile bug fixes
> re-trained HGEMM hip_lite and asm_full to match Tensile bug fixes

- clients/gtest/gemm_ex_gtest.cpp
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bjlk_HBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bljk_HBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bjlk_HBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bljk_HBH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bjlk_HBH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bljk_HBH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bjlk_HBH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bljk_HBH.yaml
- YAML logic files from Tensile  PR 338
- Tensile PR 338 sets VW=1 for hpa_hgemm for hip where m == 1 || n == 1 || k == 1
- It removes known_bugs for hpa_hgemm
> VW=1 for hpa_hgemm to remove known bug

- clients/gtest/gemm_gtest.cpp
"known_bug" prefix changed to "quick" for bugs removed by rocBLAS PR#350
> known bugs removed by rocBLAS PR#350

- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bljk_HB.yaml
-  re-trained gfx906 HGEMM asm_full to match Tensile bug fixes
-  re-trained HGEMM hip_lite and gfx900 asm_full to match Tensile bug fixes
> re-trained gfx906 HGEMM asm_full to match Tensile bug fixes

- clients/gtest/CMakeLists.txt
- clients/gtest/gemm_strided_batched_ex_gtest.cpp
- clients/gtest/gemm_strided_batched_gtest.cpp
- clients/include/testing_gemm_strided_batched_ex.hpp
- clients/include/utility.h
- library/include/rocblas-functions.h
- library/include/rocblas-types.h
- library/src/blas_ex/rocblas_gemm_ex.cpp
- library/src/blas_ex/rocblas_gemm_ex.hpp
Add mixed precision gemm for strided batched matrices
> gemm_strided_batched_ex

- library/src/blas3/Tensile/gemm.cpp
Reverts ROCmSoftwarePlatform/rocBLAS#366
> Revert "Fix incorrect chunking in CALL_TENSILE of gemm.cpp"

- clients/gtest/gemm_gtest.cpp
- clients/gtest/gemm_strided_batched_gtest.cpp
Add gemm and gemm_strided_batched tests from MIOpen sizes
> MIOpen sizes

- clients/benchmarks/client.cpp
- clients/include/testing_gemm_strided_batched_ex.hpp
Add code to enable gemm_strided_batched_ex benchmarking
> add gemm_strided_batched_ex benchmarking

- clients/include/testing_logging.hpp
Add logging test for new function gemm_strided_batched_ex
> gemm_strided_batched_ex logging test

- clients/gtest/gemm_gtest.cpp
- clients/include/testing_gemm_strided_batched_ex.hpp
> correct typos

- clients/gtest/gemm_strided_batched_ex_gtest.cpp
- clients/gtest/gemm_strided_batched_gtest.cpp
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_HBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_HBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_HBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_HBH.yaml
-  re-trained all existing gfx900/gfx906 logic files
-  added gfx906 logic files for HPA HGEMM
> re-trained gfx900/gfx906 logic files

- Jenkinsfile
> diabling old rocm1.7 CI build

- clients/gtest/known_bugs.yaml
> Add known bugs for the new Tensile code

- scripts/performance/benchmark_p1b3.sh
This will add a performance test script for p1b3 benchmark sizes.
Added scripts/performance/benchmark_p1b3.sh
> add performance test script for p1b3 benchmare sizes

- clients/gtest/rocblas_gtest_main.cpp
- clients/include/utility.h
Search for rocblas_gtest.data in the same directory as rocblas-test
> Search for rocblas_gtest.data in the same directory as rocblas-test

- library/src/blas3/Tensile/gemm.cpp
> Gemm unmacro

- clients/common/cblas_interface.cpp
- clients/include/utility.h
Fix packInt8 index overflow introduced by changes made during review of PR420.
> Fix packInt8 index overflow from PR420

- clients/gtest/CMakeLists.txt
Adds TRSM tests to the test suite
> Adding TRSM tests back to build

- CMakeLists.txt
> use tensile_fork variable in CMakeLists.txt

- Jenkinsfile
-  Updating Jenkinsfile to run on rocm2.0
> Updating Jenkinsfile to 2.0

- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_4xi8BH.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_4xi8BH.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_4xi8BH.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_4xi8BH.yaml
vega20 igemm asm yaml files. These will call assembly igemm on vega20.
> initial igemm asm yaml files

- clients/gtest/gemm_gtest.yaml
> Add GEMM K=384 tests

- CMakeLists.txt
- use tensile-tag so build can be reproduced
> set tensile_tag = v4.7.1

- CMakeLists.txt
- Change tensile_tag back to master-rocm-2.1 to pull latest Tensile from master-rocm-2.1 branch
> set tensile_tag back to master-rocm-2.1

- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_DB.yaml
rocblas-test passed on a lab gfx906 box.
> DGEMM NT k=256 tuning

- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bjlk_4xi8BH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bjlk_HBH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bljk_4xi8BH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bljk_HBH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bjlk_4xi8BH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bjlk_HBH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bljk_4xi8BH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bljk_HBH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bljk_SB.yaml
Full testing passed on both Vega 10 and Vega 20.
> migrate hip*.yaml from asm_full to hip_lite

- CMakeLists.txt
> fix version number

- clients/gtest/rocblas_gtest_main.cpp
- try adding ConfigurableEventListner from https://gist.github.com/elliotchance/8215283 
- This may reduce the size of Jenkins log files
> try adding ConfigurableEventListner to reduce Jenkins log file size

- scripts/performance/dtrsm_hpl_list1.sh
- scripts/performance/dtrsm_hpl_list2.sh
missing dtrsm list 2 does not have padded lda for 384 as not provided
> adding performance scripts for dtrsm hpl

- scripts/performance/dgemm_hpl_list1.sh
- scripts/performance/dgemm_hpl_list2.sh
- scripts/performance/dgemm_hpl_list3.sh
- scripts/performance/dgemm_hpl_list4.sh
- scripts/performance/dtrsm_hpl_list1.sh
- scripts/performance/dtrsm_hpl_list2.sh
- Update --ldc to intended values.
- Add --initialization trig_float to all runs.
> update ldc; add --initialization trig_float to all runs

- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_DB.yaml
Full rocblas-test passed with master as well as master-rocm-2.2 on both Vega 10 and Vega 20.
> Feb 24 version1 DGEMM NT sizes

- clients/benchmarks/client.cpp
> Add back GEMM half-precision cases to rocblas-bench

- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_DB.yaml
Full rocblas-test passed on both Vega 10 and Vega 20.
> Feb 24 version2 DGEMM NT sizes

- clients/benchmarks/client.cpp
- clients/gtest/blas1_gtest.cpp
- clients/gtest/blas1_gtest.yaml
- clients/gtest/geam_gtest.cpp
- clients/gtest/gemm_gtest.cpp
- clients/gtest/gemv_gtest.cpp
- clients/gtest/ger_gtest.cpp
- clients/gtest/set_get_matrix_gtest.cpp
- clients/gtest/set_get_vector_gtest.cpp
- clients/gtest/symv_gtest.cpp
- clients/gtest/syr_gtest.cpp
- clients/gtest/trsm_gtest.cpp
- clients/gtest/trsv_gtest.cpp
- clients/gtest/trtri_gtest.cpp
- clients/include/rocblas_arguments.hpp
- clients/include/rocblas_random.hpp
- clients/include/rocblas_test.hpp
- clients/include/testing_axpy.hpp
- clients/include/testing_gemm.hpp
- clients/include/testing_gemm_ex.hpp
- clients/include/testing_gemm_parallel.hpp
- clients/include/testing_gemm_strided_batched.hpp
- clients/include/testing_gemm_strided_batched_ex.hpp
- clients/include/testing_logging.hpp
- clients/include/utility.hpp
- library/src/blas1/reduction.h
- library/src/blas3/Tensile/gemm.cpp
- library/src/include/logging.h
Cosmetic changes for code consistency and simplification; also reenable passing iamin tests
> Minor cosmetic changes; reenable passing iamin tests

- clients/gtest/gemm_strided_batched_gtest.yaml
- clients/include/rocblas_init.hpp
- clients/include/testing_gemm_strided_batched_ex.hpp
Add tests for i8_r/i32_r gemm_strided_batched_ex.
> i8_r/i32_r tests for gemm_strided_batched_ex

- Jenkinsfile
Jenkinsfile needs to run on rocm2.2
> Updating to rocm2.2

- clients/benchmarks/CMakeLists.txt
- clients/gtest/CMakeLists.txt
- clients/samples/CMakeLists.txt
HOT_FIX merge into master
resolves SWDEV-182629
- need to add include directory /opt/rocm/hsa/include for file hsa/hsa.h
> add /opt/rocm/hsa/include to target_include_directories

- Jenkinsfile
> Updating to rocm2.2 for Jenkins Builds

- Jenkinsfile
-  Only project specific Jenkins configuration is stored in the project repository
-  Jenkins shared library at https://github.com/ROCmSoftwarePlatform/rocJenkins stores the common configuration including rocm version and docker image names. We will be able to centrally update the versioning. Some flexibility is lost but we gain easier management. 
- Unused features in the current Jenkinsfile was not implemented in the shared library. New features will be added in the upcoming weeks.
- Shared library was designed to support Jenkins Blue Ocean UI in the future.
> Refactor of Jenkinsfile; switching to use shared library

- scripts/performance/dgemm_hpl_small1.sh
- scripts/performance/dgemm_hpl_small2.sh
adding performance scripts for small sizes
> adding small dgemm sizes

- clients/include/testing_trsm_ex.hpp
- library/include/rocblas-functions.h
- library/src/blas_ex/rocblas_trsm_ex.cpp
#172044
-  Added usage info to trsm_ex doc
-  Fixed bugs that caused part of docs not to show up in readthedocs
-  Remove some unused variables
> Added trsm usage info to docs

- clients/gtest/blas1_gtest.yaml
Disable IAMIN tests until random non-deterministic errors figured out
> Once again disable IAMIN tests until non-deterministic errors figured out

- clients/gtest/gemm_gtest.cpp
- clients/gtest/gemm_gtest.yaml
- clients/gtest/gemm_strided_batched_gtest.yaml
- clients/gtest/gemv_gtest.yaml
- clients/include/rocblas_data.hpp
- clients/include/rocblas_datatype2string.hpp
- clients/include/rocblas_init.hpp
- clients/include/rocblas_math.hpp
- clients/include/rocblas_test.hpp
- clients/include/testing_gemm.hpp
- clients/include/testing_gemm_ex.hpp
- clients/include/testing_gemm_strided_batched.hpp
- clients/include/testing_gemm_strided_batched_ex.hpp
- clients/include/testing_gemv.hpp
- clients/include/unit.hpp
- docker/dockerfile-build-fedora
- install.sh
Adds NaN tests for gemv, gemm, and gemm_ex.
> Add NaN tests to GEMV and GEMM*

- docker/dockerfile-build-fedora
- install.sh
> Fix dependency on python3*-PyYAML on CentOS/Fedora/RHEL

- docker/dockerfile-build-fedora
- install.sh
> Fix dependency on python3*-PyYAML on CentOS/Fedora/RHEL (#543)

- clients/include/near.hpp
- clients/include/rocblas.hpp
- clients/include/rocblas_math.hpp
- clients/include/testing_logging.hpp
- library/src/blas1/rocblas_amax_amin.h
- library/src/blas1/rocblas_asum.cpp
- library/src/blas1/rocblas_axpy.cpp
- library/src/blas1/rocblas_copy.cpp
- library/src/blas1/rocblas_dot.cpp
- library/src/blas1/rocblas_nrm2.cpp
- library/src/blas1/rocblas_scal.cpp
- library/src/blas1/rocblas_swap.cpp
- library/src/blas2/rocblas_gemv.cpp
- library/src/blas2/rocblas_ger.cpp
- library/src/blas2/rocblas_syr.cpp
- library/src/blas2/rocblas_trsv.cpp
- library/src/blas3/Tensile/gemm.cpp
- library/src/blas3/rocblas_geam.cpp
- library/src/blas3/rocblas_trmm.cpp
- library/src/blas3/rocblas_trsm.cpp
- library/src/blas3/rocblas_trtri_batched.cpp
- library/src/include/utility.h
https://github.com/ROCmSoftwarePlatform/rocBLAS/pull/551
> Following DR2387, explicitly declare const[expr] variable templates static

- CMakeLists.txt
- cmake/virtualenv.cmake
Required for the switch away from Python 2 in Tensile.
> Switch to Python 3 for virtual environment.

- library/src/blas3/rocblas_trsm.cpp
resolves #188018
-  Added a switch statement to check arch when decided which GEMM to call
> Fixing Vega10 Trsm Regression

- library/src/blas3/rocblas_trsm.cpp
resolves #___
-  optimize performance of one of trsm kernel copy_void_ptr_matrix_trsm.
-  copy matrix use template to decide type is faster than void copy with size of type
In our test case:  WORKBUF_TRSM_B_CHNK=32768 ./clients/staging/rocblas-bench -r d -f trsm -m 256 --lda 256 -n 32768 --ldb 256 --side L --uplo L --transposeA N --diag U -v 1 -i 10, origin copy_void_ptr_matrix_trsm takes 739us, new copy_matrix_trsm takes 384us.
original trace:
new trace:
> Trsm: use template matrix copy to replace void matrix copy

- library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Ailk_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Ailk_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Ailk_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Ailk_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Alik_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Alik_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Alik_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bjlk_BBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bljk_BBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bjlk_BBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bljk_BBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_DB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_SB.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bjlk_BBH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bljk_BBH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bjlk_BBH.yaml
- library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bljk_BBH.yaml
Follows fix in Tensile for spelling of IndiciesLD to IndicesLD.
> Fixing spelling of indices from indicies

- clients/benchmarks/client.cpp
-  Re-arranged includes to ensure the formatter doesn't reorder them
- Passed on local Ubuntu16 Jenkins instance
- Ubuntu18 Jenkins job in-progress
> fixed sorted headers in client.cpp

- .github/CONTRIBUTING.md
> Add coding guidelines

- library/include/rocblas_bfloat16.h
- Changes hip_runtime.h back to hip_runtime_api.h
> Restore contents of commit a82c082

- CMakeLists.txt
- bump_develop_version.sh
- bump_master_version.sh
> Periodic merge of master into develop before merge of develop into master

- library/src/CMakeLists.txt
- This PR depends on Tensile PR#588. It needs to be merged after Tensile PR#588 is merged
> code_object_version switch V2 or V3

- CMakeLists.txt
- install.sh
- library/src/CMakeLists.txt
- add -o|--cov option to install.sh so code_object_version will be passed from rocBLAS to Tensile
- make Tensile_CODE_OBJECT_VERSION a CACHE variable in CMakeLists.txt
> make code_object_version an install.sh option

- CMakeLists.txt
- bump_develop_version.sh
- bump_master_version.sh
> merge master into develop for ROCm 2.7 feature complete

- library/include/rocblas_bfloat16.h
- cherry pick change from develop into master
> Check hip-clang as well. (#630)

- Jenkinsfile
> Added CentOS Vega 10 and Vega 20 jobs

- CMakeLists.txt
- Pulls Tensile with changes in Tensile PR#619
- This Tensile PR#619 includes:
- Fix loop compare against 1 for SuppressNoLoadLoop mode
- Correct argument order in call to TensileCreateLibraryCmake
> ROCm2.8 hot fix: pull fixed Tensile

- CMakeLists.txt
pull hot fix2 in Tensile PR#632
> ROCm2.8 hot fix2: pull fixed Tensile

- Jenkinsfile
- docker/dockerfile-build-ubuntu-rock
> Trying to fix permissions issues (master-hip-clang)

- CMakeLists.txt
> <hip/hip_hcc.h> for HipSolutionAdapter.cpp (master branch)

- CMakeLists.txt
- bump_develop_version.sh
- bump_master_version.sh
This is for merging master into develop before merging develop into master.
> ROCm 2.9 merge master into develop

- Jenkinsfile
- docker/dockerfile-build-ubuntu-rock
> Fixed Jenkinsfile and dockerfile permissions issues

- CMakeLists.txt
Tensile tag updated to point to "hot fix to restore loading of DGEMM replacement kernels".
> hot fix to restore loading of DGEMM replacement kernels

- CMakeLists.txt
- Jenkinsfile
- clients/CMakeLists.txt
- clients/benchmarks/CMakeLists.txt
- clients/gtest/CMakeLists.txt
- cmake/os-detection.cmake
- docker/dockerfile-build-sles
- docker/dockerfile-install-sles
- install.sh
Adding the SLES support commits that are in develop into master.
> SLES support

- clients/benchmarks/CMakeLists.txt
- clients/gtest/CMakeLists.txt
Adding the search clang 10 include folder for SLES as well.
> Supporting clang10 for SLES

- clients/gtest/blas1_gtest.yaml
fixes nightly test by only comparing double results to cbas
> fix nightly tests nrm2 and asum

- clients/include/testing_asum_batched.hpp
- clients/include/testing_asum_strided_batched.hpp
- clients/include/testing_nrm2_batched.hpp
- clients/include/testing_nrm2_strided_batched.hpp
fixes inconsistences in batch output for edge case arguments
> fix batch tests edge cases for nrm2,asum

- clients/benchmarks/CMakeLists.txt
- clients/gtest/CMakeLists.txt
- clients/samples/CMakeLists.txt
- header_compilation_tests.sh
Lets hip include auto set HIP_PLATFORM_HCC when using HIP tools
> SWDEV-205693-hip-platform-warning

- library/src/blas1/rocblas_scal.cpp
- library/src/blas1/rocblas_scal.hpp
- library/src/blas1/rocblas_scal_batched.cpp
- library/src/blas1/rocblas_scal_strided_batched.cpp
Removed option for array of scalars on host for scal.
> Removed array of alphas on host for scal.

- library/src/blas3/Tensile/gemm_strided_batched.cpp
* builds were broken and I saw this clang format diff
> fix clang formatting

- library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Ailk_Bjlk_ZB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_ZB.yaml
merged and massaged square zgemm logic files
> Improved zgemm performance

- header_compilation_tests.sh
look for CMakeCache.txt in build dir
> spack build is outside source directory

- clients/include/flops.hpp
Fixing some changes that were previously made to flop functions
> Fixing flop count for gemv and trsm

- library/src/blas3/Tensile/Logic/asm_ci/vega20_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_ci/vega20_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_ci/vega20_Cijk_Alik_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_HB.yaml
- library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_HB.yaml
adding merged logic for msra_hgemm.
performance results:
gemm_strided_batched h NN m=64 n=128 k=128 batch=1024   15149.5
gemm_strided_batched h NT m=64 n=128 k=128 batch=1024   16269.4
gemm_strided_batched h TN m=128 n=128 k=64 batch=1024   14762.3
> logic for msra hgemm

- .gitmodules
- docker/dockerfile-build-sles
- install.sh
> Switch to prebuilt AMD blis 2.0

- docs/run_doc.sh
- docs/source/addtest.rst
- docs/source/clients.rst
- docs/source/conf.py
- docs/source/contributing.rst
- docs/source/design.rst
- docs/source/designdoc.rst
- docs/source/index.rst
- docs/source/orga.rst
- docs/source/usermanual.rst
- Add design doc files separate from user guide
- There are files for
- Introduction
- Library Source Code Organization
- Contributing
- Adding Tests
- Clients
> Design doc

- library/src/CMakeLists.txt
- The RUNPATH will be set only if ROCM_RPATH is defined in the ENV
> Adding RUNPATH to rocBLAS lib

- clients/benchmarks/client.cpp
- clients/gtest/CMakeLists.txt
- clients/gtest/rocblas_gtest.yaml
- clients/gtest/tbmv_gtest.cpp
- clients/gtest/tbmv_gtest.yaml
- clients/include/cblas_interface.hpp
- clients/include/flops.hpp
- clients/include/rocblas.hpp
- clients/include/testing_gemv.hpp
- clients/include/testing_tbmv.hpp
- library/include/rocblas-functions.h
- library/src/CMakeLists.txt
- library/src/blas2/rocblas_tbmv.cpp
- library/src/blas2/rocblas_tbmv.hpp
Functional s/d/c/z versions of L2 BLAS function tbmv. Un-optimized. Implementation is based on gemv.
Tbmv is important for implementation of tbsv which is needed in the future.
Tbmv is a triangular banded matrix - vector multiply. See comments in code for explanation, or see LAPACK.
SWDEV-214265
> Functional tbmv

- scripts/performance/blas/alltime.py
- scripts/performance/blas/datagraphs.asy
- scripts/performance/blas/getspecs.py
- scripts/performance/blas/stats.asy
- scripts/performance/blas/timing.py
- scripts/performance/blas/utils.asy
Addition of performance scripts to benchmark user defined problem sizes, using rocblas-bench.
> Perf scripts

- scripts/performance/sgemm_dlrm_small_medium.sh
This commit does not impact rocBLAS build in any way.
> Latest small+medium DLRM sizes from Dieterich

- scripts/performance/blas/alltime.py
Some cleanup and adding flag to help with automating performance tracking
> Adding flag for second data file dir

- docker/dockerfile-build-centos
- docker/dockerfile-build-ubuntu-rock
> Remove deprecated rocm_smi64 package from CI

- install.sh
This option will be used when it is build by the jenkins.
This change will enable users to select proper rocblas lib when multiple versions are installed.
> Adding an option to skip creating ld.so.conf entry

- docker/dockerfile-build-sles
- docker/dockerfile-build-ubuntu-rock
- install.sh
> Change to wget in install.sh and add dependencies for all linux distros

- library/src/blas3/Tensile/Logic/asm_full/arcturus_Cijk_Alik_Bljk_BBH.yaml
Full rocblas-test --gtest_filter=-\*known_bug\* passed on gfx908.
> add 8k sizes for BF16 TN

- .jenkins/Extended.groovy
- .jenkins/PreCheckin.groovy
> Reduce CI load by removing redundant testing

- .jenkins/Debug.groovy
- .jenkins/Extended.groovy
- .jenkins/Extended_TOT_Tensile.groovy
- .jenkins/PreCheckin.groovy
- .jenkins/PreCheckin_TOT_Tensile.groovy
> Added setProperties function call to Jenkinsfiles

- library/src/blas3/Tensile/Logic/asm_full/arcturus_Cijk_Ailk_Bjlk_SB.yaml
- library/src/blas3/Tensile/Logic/asm_full/arcturus_Cijk_Alik_Bljk_SB.yaml
> Added tuned arcturus transformer configs

- install.sh
> remove space

- clients/benchmarks/client.cpp
- clients/common/rocblas_gentest.py
- clients/gtest/CMakeLists.txt
- clients/gtest/hpr_gtest.cpp
- clients/gtest/hpr_gtest.yaml
- clients/gtest/rocblas_gtest.yaml
- clients/include/cblas_interface.hpp
- clients/include/flops.hpp
- clients/include/rocblas.hpp
- clients/include/testing_hpr.hpp
- clients/include/testing_hpr_batched.hpp
- clients/include/testing_hpr_strided_batched.hpp
- library/include/rocblas-functions.h
- library/src/CMakeLists.txt
- library/src/blas2/rocblas_hpr.cpp
- library/src/blas2/rocblas_hpr.hpp
- library/src/blas2/rocblas_hpr_batched.cpp
- library/src/blas2/rocblas_hpr_strided_batched.cpp
- library/src/include/utility.h
See [documentation](http://www.netlib.org/lapack/explore-html/d6/dee/group__complex__blas__level2_gac98100eee08124fb7a5d55effbb85a65.html#gac98100eee08124fb7a5d55effbb85a65).
Pretty much spr with tiny logic changes in the kernel.
> Funcitonal HPR

- clients/benchmarks/client.cpp
- clients/gtest/trmm_gtest.cpp
- clients/gtest/trmm_gtest.yaml
- clients/include/rocblas.hpp
- clients/include/testing_trmm.hpp
- clients/include/unit.hpp
- library/include/rocblas-functions.h
- library/src/blas1/rocblas_copy.cpp
- library/src/blas1/rocblas_copy.hpp
- library/src/blas1/rocblas_copy_batched.cpp
- library/src/blas1/rocblas_copy_strided_batched.cpp
- library/src/blas2/rocblas_tbmv.hpp
- library/src/blas2/tpmv_template.hpp
- library/src/blas2/trmv_template.hpp
- library/src/blas3/rocblas_trmm.cpp
- library/src/blas3/rocblas_trmm.hpp
- add complex functions rocblas_ctrmm and rocblas_ztrmm.
- add CONJ template parameter to internal function rocblas_copy_template. This provides the option for  conjugation with copy.
> add complex rocblas_ctrmm and rocblas_ztrmm

- clients/gtest/geruc_gtest.yaml
With all the additional functions reducing the test load
> reducing testing load

- library/src/blas3/Tensile/Logic/asm_full/arcturus_Cijk_Ailk_Bjlk_BBH.yaml
- library/src/blas3/Tensile/Logic/asm_full/arcturus_Cijk_Ailk_Bljk_BBH.yaml
These 3 arcturus BF16 logic files require Lee's PR#977 for rocblas-test to pass on arcturus.
> Jimmy's arcturus BF16 logic files merged with TN replacement kernel

- docker/dockerfile-build-centos
- docker/dockerfile-build-fedora
- docker/dockerfile-build-ubuntu
- docker/dockerfile-build-ubuntu-rock
- docker/dockerfile-install-centos
- docker/dockerfile-install-fedora
- docker/dockerfile-install-ubuntu
change individual email to rocblas-maintainer@amd.com
> no individual email addresses

- clients/benchmarks/client.cpp
- clients/gtest/CMakeLists.txt
- clients/gtest/her2k_gtest.cpp
- clients/gtest/her2k_gtest.yaml
- clients/gtest/syr2k_gtest.cpp
- clients/gtest/syr2k_gtest.yaml
- clients/include/cblas_interface.hpp
- clients/include/flops.hpp
- clients/include/rocblas.hpp
- clients/include/rocblas_template.yaml
- clients/include/testing_her2k.hpp
- clients/include/testing_her2k_batched.hpp
- clients/include/testing_her2k_strided_batched.hpp
- clients/include/testing_syr2k.hpp
- clients/include/testing_syr2k_batched.hpp
- clients/include/testing_syr2k_strided_batched.hpp
- library/include/rocblas-functions.h
- library/src/CMakeLists.txt
- library/src/blas3/rocblas_her2k.cpp
- library/src/blas3/rocblas_her2k.hpp
- library/src/blas3/rocblas_her2k_batched.cpp
- library/src/blas3/rocblas_her2k_strided_batched.cpp
- library/src/blas3/rocblas_syr2k.cpp
- library/src/blas3/rocblas_syr2k.hpp
- library/src/blas3/rocblas_syr2k_batched.cpp
- library/src/blas3/rocblas_syr2k_strided_batched.cpp
- functional syr2k and her2k
- removed /efi partition formatting feature
- Daine I think your commit was temporarily added in a rebase that is why you are in the commit
> functional syr2k and her2k

- clients/include/testing_herk_batched.hpp
- clients/include/testing_herk_strided_batched.hpp
- clients/include/testing_sbmv_batched.hpp
- clients/include/testing_spmv_batched.hpp
- clients/include/testing_symv_batched.hpp
- clients/include/testing_syrk_batched.hpp
- clients/include/testing_syrk_strided_batched.hpp
* fixes norm check call
* will add more commits
> flip norm_check batch lda args

- library/include/rocblas-functions.h
Fixes descriptions of strided batched data in non-strided manner
> doxygen doc fixes

- clients/benchmarks/client.cpp
- clients/gtest/CMakeLists.txt
- clients/gtest/hemm_gtest.cpp
- clients/gtest/hemm_gtest.yaml
- clients/gtest/rocblas_gtest.yaml
- clients/gtest/symm_gtest.cpp
- clients/gtest/symm_gtest.yaml
- clients/include/cblas_interface.hpp
- clients/include/flops.hpp
- clients/include/rocblas.hpp
- clients/include/testing_symm_hemm.hpp
- clients/include/testing_symm_hemm_batched.hpp
- clients/include/testing_symm_hemm_strided_batched.hpp
- library/include/rocblas-functions.h
- library/src/CMakeLists.txt
- library/src/blas3/rocblas_hemm.cpp
- library/src/blas3/rocblas_hemm.hpp
- library/src/blas3/rocblas_hemm_batched.cpp
- library/src/blas3/rocblas_hemm_strided_batched.cpp
- library/src/blas3/rocblas_symm.cpp
- library/src/blas3/rocblas_symm.hpp
- library/src/blas3/rocblas_symm_batched.cpp
- library/src/blas3/rocblas_symm_strided_batched.cpp
functional versions using tiling scheme
Current Test times
128 tests from quick/hemm (533 ms total)
50 tests from pre_checkin/hemm (529 ms total)
32 tests from nightly/hemm (16504 ms total)
256 tests from quick/hemm_batched (32 ms total)
98 tests from pre_checkin/hemm_batched (4129 ms total)
32 tests from nightly/hemm_batched (32113 ms total)
256 tests from quick/hemm_strided_batched (35 ms total)
98 tests from pre_checkin/hemm_strided_batched (3791 ms total)
32 tests from nightly/hemm_strided_batched (31944 ms total)
982 tests from 9 test cases ran. (89610 ms total)
64 tests from quick/symm (513 ms total)
97 tests from pre_checkin/symm (663 ms total)
64 tests from nightly/symm (19971 ms total)
128 tests from quick/symm_batched (15 ms total)
193 tests from pre_checkin/symm_batched (4934 …
> L3 symm hemm func

- clients/include/testing_spmv.hpp
- clients/include/testing_spmv_batched.hpp
- clients/include/testing_spmv_strided_batched.hpp
- clients/include/testing_symv.hpp
- clients/include/testing_symv_batched.hpp
- clients/include/testing_symv_strided_batched.hpp
- library/src/blas2/rocblas_sbmv.hpp
- library/src/blas2/rocblas_spmv.hpp
- library/src/blas2/rocblas_symv.hpp
* use hXmv strategies as optimization baseline 
* adds bandwidth to benchmark
> baseline opt and add bandwidth

- clients/gtest/geam_gtest.cpp
- clients/gtest/geam_gtest.yaml
- clients/include/rocblas.hpp
- clients/include/testing_geam.hpp
- library/include/rocblas-functions.h
- library/src/blas3/geam_device.h
- library/src/blas3/rocblas_geam.cpp
> geam complex

- library/include/rocblas-types.h
> Use _Float16 only if clang >= 10 

- cmake/virtualenv.cmake
- docker/dockerfile-build-centos
- docker/dockerfile-build-sles
- docker/dockerfile-build-ubuntu-rock
- install.sh
This is based off develop branch not 3.0 like the earlier one, just adds dependency to Paul's simplification to use python3 venv.
> Virtual env fix

- clients/common/cblas_interface.cpp
* adds openmp to speed up reference herkx calculations
> trial use of omp in client/common

- scripts/performance/blas/alltime.py
- scripts/performance/blas/timing.py
> add cold_iters and no figure options

- clients/common/utility.cpp
> Fix trivial off-by-1 error (1 too small)

- clients/common/cblas_interface.cpp
- library/src/blas3/rocblas_syr2k.hpp
* trying to match herkx external reference
> allow A*B result with imaginary diagonals

- docs/cleanup_text.sh
See https://github.com/RadeonOpenCompute/ROCm_Documentation/pull/72 for details.
This is a general cleanup script which should be in every project's toolkit.
> New tool to clean up text, especially .rst files

- library/src/blas3/Tensile/Logic/asm_full/arcturus_Cijk_Ailk_Bjlk_SB.yaml
Add arcturus SGEMM NT HPL sizes for k=384 and n=m,2\*m,m/2 for m=384\*i where i goes from 1 to 20.
> arcturus SGEMM NT HPL sizes for k=384 and n=m,2*m,m/2

- clients/include/argument_model.hpp
> append perf csv

- library/include/rocblas-complex-types.h
* adds include for file to be standalone
> adds export include for rocblas_complex

- library/src/include/rocblas_ostream.hpp
Make `rocblas_cout` and `rocblas_cerr` have thread-local `rocblas_ostream`
> Make rocblas_cout / rocblas_cerr's rocblas_ostream thread-local

- clients/common/rocblas_parse_data.cpp
* fix allows filtering with yaml input
> fix argv list parsing

- clients/include/argument_model.hpp
- clients/include/bytes.hpp
- clients/include/flops.hpp
- clients/include/testing_dot.hpp
- clients/include/testing_dot_batched.hpp
- clients/include/testing_dot_strided_batched.hpp
- clients/include/testing_nrm2.hpp
- clients/include/testing_nrm2_batched.hpp
- clients/include/testing_nrm2_strided_batched.hpp
*  makes bench call use newer byte helpers and consistent Giga units
> Adjust bench log

- clients/include/norm.hpp
- clients/include/rocblas_init.hpp
- clients/include/testing_asum_batched.hpp
- clients/include/testing_axpy_batched.hpp
- clients/include/testing_gbmv_batched.hpp
- clients/include/testing_gemm_batched.hpp
- clients/include/testing_gemm_batched_ex.hpp
- clients/include/testing_hbmv_batched.hpp
- clients/include/testing_hemv_batched.hpp
- clients/include/testing_her2_batched.hpp
- clients/include/testing_her_batched.hpp
- clients/include/testing_herk_batched.hpp
- clients/include/testing_herk_strided_batched.hpp
- clients/include/testing_hpmv_batched.hpp
- clients/include/testing_hpr2_batched.hpp
- clients/include/testing_hpr_batched.hpp
- clients/include/testing_hpr_strided_batched.hpp
- clients/include/testing_reduction_batched.hpp
- clients/include/testing_rotmg_batched.hpp
- clients/include/testing_spmv_batched.hpp
- clients/include/testing_spr2_batched.hpp
- clients/include/testing_spr_batched.hpp
- clients/include/testing_syrk_batched.hpp
- clients/include/testing_syrk_strided_batched.hpp
- clients/include/testing_tbmv_batched.hpp
- clients/include/testing_tpmv_batched.hpp
- clients/include/testing_trmv_batched.hpp
(cherry picked from commit 6b08a6cfcabc30b0560a8a5acd583010f38c59a5)
For [SWDEV-220984](http://ontrack-internal.amd.com/browse/SWDEV-220984).
> Batched memcheck fixes (#1115)

- clients/gtest/ger_gtest.yaml
- clients/gtest/geruc_gtest.yaml
- library/src/blas2/rocblas_ger.hpp
* fixes potential read out of bounds
> cherry-picks ger fix

- clients/gtest/ger_gtest.yaml
- clients/gtest/geruc_gtest.yaml
- library/src/blas2/rocblas_ger.hpp
* updates tests even though they don't yet catch bug due to guard pads
> fix potential read out of bounds

- library/src/CMakeLists.txt
* python3 as Centos8 may not have python without alternatives
> use python3 

- library/src/blas2/rocblas_trsv_substitution.hpp
> Trsv patch 21.40

- CMakeLists.txt
* merge hotfix into release branch
> set arch variables in clients-only build (#875)

- library/src/include/rocblas_device_malloc.hpp
- library/src/template-proto.py
resolves #___
-  Include directory updated to include/component_nm structure
-  Dep Changes of header inclusions added here.
-
> Include Target Reorg Dep Changes

- clients/samples/example_solver_rocblas.cpp
- library/src/CMakeLists.txt
resolves #___
- Generated headers moved to reflect reorg structure
- Header inclusions updated
> Include reorg - fix for internal Header

- library/src/tensile_host.cpp
resolves #___
- fix for updating to new Tensile lib path after reorg
-
-
> Tensile Lib Path Reorg

- library/src/CMakeLists.txt
- library/src/tensile_host.cpp
> Tensile Lib Path Debug

- clients/CMakeLists.txt
- clients/benchmarks/CMakeLists.txt
- clients/common/rocblas_arguments.cpp
- clients/common/utility.cpp
- clients/gtest/CMakeLists.txt
- clients/gtest/general_gtest.cpp
- clients/gtest/multiheaded_gtest.cpp
- clients/include/blas_ex/testing_gemm_ex.hpp
- clients/include/blas_ex/testing_gemm_ext2.hpp
- clients/include/rocblas.hpp
- clients/include/rocblas_arguments.hpp
- clients/include/rocblas_init.hpp
- clients/include/rocblas_solve.hpp
- clients/include/rocblas_test.hpp
- clients/include/utility.hpp
- clients/samples/CMakeLists.txt
resolves #___
- src/include header direct inclusion changes reverted
-
-
> Include Path - revert direct src include inclusions

- CONTRIBUTING.rst
Add link to repo and suggest formatting change for branches.
> Fix typo and specify repo

- clients/benchmarks/CMakeLists.txt
- clients/gtest/CMakeLists.txt
resolves #1241 
- Updated internal includes list for clients directory
> Hotfix for build error when compiled with '--clients-only' option 

- tensile_tag.txt
Updating to capture the hotfix in [Tensile #1575](https://github.com/ROCmSoftwarePlatform/Tensile/pull/1575).
> Update tensile tag for hipModuleLoad hotfix

- clients/benchmarks/CMakeLists.txt
> build gemm-tune only in tensile builds
