CMakeLists.txt

-  set default building as releas 
-  remove rocblas library building from client building dependency, otherwise it occurs 1-hour building every time
-  
Please enter the commit message for your changes. Lines starting

remove client dependecy on building rocblas libraray

---

library/src/blas3/Tensile/gemm.cpp

fixing conjugate transpose of read data type leading to problem unsupported; correct behavior is that conjugate transpose converts to transpose
I'm confident this fixed the problem, however I can't test, because of hangs.

fixing Tensile problemNotSupported bug

---

CMakeLists.txt
Jenkinsfile
clients/CMakeLists.txt
clients/common/unit.cpp

-  speedup the google unit check by unrolling the loop 
-  make the naming consistent: XXX_ROOT

change lapack -> lapack_root; speedup unit check by unroll hint

---

CMakeLists.txt

resolves #___
-  make CMAKE_BUILD_TYPE display in ccmake
-  pass CMAKE_BUILD_TYPE  to library build so that we can set it to Release or Debug
to control debug printing in gemm with #ifndef NDEBUG

pass CMAKE_BUILD_TYPE to library build

---

CMakeLists.txt
README.md

The common use is a user building rocBLAS libraries and sample code. The CMakeList.txt options are set so that the common use can be configured with the command  "cmake ..".

set CMake defaults for common use

---

CMakeLists.txt
clients/benchmarks/CMakeLists.txt
clients/gtest/CMakeLists.txt
clients/samples/CMakeLists.txt

-  If the user sets the cmake install prefix at configure time, set the install directory of the library to match
-  Hardcode a fallback PATH to the find_package to look into /opt/rocm/rocblas for rocblas CONFIG mode, if it doesn't find rocblas locally in build directory
-

cmake install fixes

---

CMakeLists.txt

-  Add support to rocblas to specify multiple backend architectures to compile for
-  defaulting to gfx803, gfx900

Add default device targets for compilation

---

library/include/rocblas-functions.h
library/src/blas2/ger_device.h
library/src/blas2/rocblas_ger.cpp

ger functions contained redundant template parameters DIM_X and DIM_Y. These are removed.

remove ger redundant template parameters DIM_X DIM_Y

---

CMakeLists.txt

-  Adding whitespace so the compiler flags do not merge together on concatenation.

Fix for compiler flags

---

library/src/blas1/rocblas_amax.cpp
library/src/blas1/rocblas_amin.cpp
library/src/blas1/rocblas_asum.cpp
library/src/blas1/rocblas_dot.cpp
library/src/blas1/rocblas_nrm2.cpp
library/src/blas3/rocblas_trsm.cpp
library/src/blas3/trtri_trsm.hpp

use unique_ptr to avoid memory leak. The changes convert existing code to use unique_ptr

use unique_ptr for hipMalloc and malloc

---

CMakeLists.txt
Jenkinsfile
clients/CMakeLists.txt
library/CMakeLists.txt

-  The super-build has targets like 'install' & 'package'
-  Allow clients to be compiled with hipcc/hcc with target architecture
flags to align with changes in compiler

Adding new targets to super-build

---

clients/benchmarks/perf_script/measurePerformance.py

resolves #___
when I execute the following command:
$python measurePerformance.py -s 64-5760:64 -f gemm -r s --transa none --transb transpose > sgemm.txt
as shown in https://github.com/ROCmSoftwarePlatform/rocBLAS/tree/develop/clients/benchmarks/perf_script/README.txt
The following error occurred：
`Traceback (most recent call last):
File "measurePerformance.py", line 307, in <module>
test_combinations = [BlasTestCombination(params[0][0], params[0][1], params[0][2], params[0][3], params[0][4], params[0][5], params[1], params[2], params[3], params[4], params[5], params[6], params[7], params[8], params[9], params[10], params[11], params[12], params[13], params[14], params[15], label) for params in test_combinations]
IndexError: tuple index out of range`
I found no param [15]. So param[15] …

bugfix no params[15] in params in test_combinations

---

clients/common/arg_check.cpp
clients/gtest/gemm_gtest.cpp
clients/gtest/gemv_gtest.cpp
clients/include/arg_check.h
clients/include/testing_gemm.hpp
clients/include/testing_gemv.hpp
library/src/blas2/rocblas_gemv.cpp

resolves #___
-  when gemm parameter beta == 0 matrix C must be set to 0, not multiplied by zero. 
-  This prevents propagation of NaN when beta == 0.
-  A test is added to verify that C is set to zero when beta == 0
-  gemm tests are also added to verify correct behavior when A, B, C, alpha, beta = nullptr

add gemm NaN and bad-arg tests

---

clients/benchmarks/perf_script/CMakeLists.txt

-  Clients should eventually install in a separate .deb package

Don't install the python performance scripts

---

clients/gtest/blas1_gtest.cpp
library/src/blas1/rocblas_dot.cpp

rocblas_dot was returning rocblas_status_success when incx<0 || incy<0, and tests were not catching the error.
Remove the return for incx<0 || incy<0. rocblas_dot gives correct behavior for incx<0||incy<0, so no change is needed other than to remove the incorrect return. Also change tests to catch this error.

correct rocblas_dot for inc<0

---

clients/include/testing_gemm.hpp

add variables number_cold_calls and number_hot_calls to testing_gemm.hpp . For rocblas_bench gemm will be called number_cold_calls before timing number_hot_calls. This will give greater repeatability for rocblas_bench timing of gemm.

add cold and hot loops to improve gemm timing repeatability

---

clients/common/rocblas_template_specialization.cpp
library/include/rocblas-functions.h

Complex and half functions are not tested or supported. Remove them from rocBLAS  rocblas-functions.h  and  rocblas_template_specialization.cpp

remove complex and half functions from API

---

library/src/blas3/Tensile/gemm.h

remove the following code which is repeated 
if (m < 0 || n < 0 || k < 0 || b_c < 0) {
return rocblas_status_invalid_size;
}

remove duplicate code for leading dimension argument validation

---

library/src/include/rocblas_unique_ptr.hpp

add static to rocblas::device_malloc to test if it avoids build fails with "rocblas::device_malloc(unsigned long) multiply defined"
This may be caused by "-Bsymbolic removal" in hcc

add static because -Bsymbolic removal in hcc

---

clients/common/rocblas_template_specialization.cpp
clients/include/rocblas.hpp
clients/include/testing_geam.hpp
library/include/rocblas-functions.h
library/src/blas3/geam_device.h
library/src/blas3/rocblas_geam.cpp

Correct geam API to move beta before B. Incorrect API is:
rocblas_status rocblas_Xgeam(handle, transA, transB, m, n, alpha, A, lda, B, ldb, beta, C, ldc)
Correct API is:
rocblas_status rocblas_Xgeam(handle, transA, transB, m, n, alpha, A, lda, beta, B, ldb, C, ldc)

correct geam API move beta before B

---

CMakeLists.txt

rocBLAS build fails if cmake 3.5.2 is used. It passes if cmake 3.5.1 is used. 
Add descriptive error message that will help users avoid the build fail with cmake 3.5.2.

add error message for cmake3.5.2

---

CMakeLists.txt
library/src/blas3/Tensile/Logic/hip_lite/Tensile_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/hip_lite/Tensile_Cijk_Ailk_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/hip_lite/Tensile_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/hip_lite/Tensile_Cijk_Ailk_Bljk_SB.yaml
library/src/blas3/Tensile/Logic/hip_lite/Tensile_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/hip_lite/Tensile_Cijk_Alik_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/hip_lite/Tensile_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/hip_lite/Tensile_Cijk_Alik_Bljk_SB.yaml
library/src/blas3/Tensile/Logic/other/README.txt

and adding empty "other" directory with README explaining its use.
The hip_lite build has only 1 pretty fast kernel for each precision/transpose. I validate them locally since Jenkins won't. However, we may get bugs if the compiler every stops working for these kernels.

adding hip_lite for architectures not supported by assembly

---

library/src/blas1/rocblas_axpy.cpp
library/src/include/definitions.h

change function rocblas_fmadd_half2 so that it returns void. The result is returned as a half2* argument, not as the function return.

fix __global__ function rocblas_fmadd_half2 to return void

---

clients/include/testing_gemm.hpp
clients/include/testing_gemm_strided_batched.hpp
clients/include/testing_trsm.hpp
library/src/blas3/Tensile/gemm.cpp

add rocblas_pointer_mode_device to gemm, gemm_strided_batched and trsm.
This is done by copying alpha and beta from device to host. TODO: change to add gemm and gemm_strided_batched kernels that handle rocblas_pointer_mode_device

gemm rocblas_pointer_mode_device

---

CMakeLists.txt
install.sh
library/src/CMakeLists.txt
library/src/blas3/Tensile/Logic/mi25_full/Tensile_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/mi25_full/Tensile_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/mi25_full/Tensile_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/mi25_full/Tensile_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/mi25_lite/Tensile_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/mi25_lite/Tensile_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/mi25_lite/Tensile_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/mi25_lite/Tensile_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/r9nano_full/Tensile_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/r9nano_full/Tensile_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/r9nano_full/Tensile_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/r9nano_full/Tensile_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/r9nano_lite/Tensile_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/r9nano_lite/Tensile_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/r9nano_lite/Tensile_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/r9nano_lite/Tensile_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/vega10_full/Tensile_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/vega10_full/Tensile_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/vega10_full/Tensile_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/vega10_full/Tensile_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/vega10_lite/Tensile_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/vega10_lite/Tensile_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/vega10_lite/Tensile_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/vega10_lite/Tensile_Cijk_Alik_Bljk_DB.yaml

Note: it looks like gemm tests aren't being run in current version of rocBLAS. I tested these config files checked into older version of rocBLAS when gemm tests were being run and it did pass.
Only 2 kernels per transposed are used for dgemm. 1 super fast kernel and 1 for M,N<2

adding dgemm assembly from Tensile v3.4.0

---

clients/gtest/set_get_pointer_mode_gtest.cpp

rocblas tests were refactored to use unique_ptr for rocblas_handle. The code in set_get_pointer_mode_gtest was not refactored when it should have been refactored. This pull request contains the required refactor for set_get_pointer_mode_gtest.

in set_get_pointer_mode_gtest use unique_ptr for rocblas_handle

---

Jenkinsfile
docker/dockerfile-build-fedora
docker/dockerfile-build-ubuntu
install.sh
library/CMakeLists.txt

-  There are no fedora builds with ROCm v1.7; disable the fedora builds until they are available
-  Update the hip dependency version
-

Disable fedora builds

---

CMakeLists.txt

tensile_tag update to get new version of Tensile. The new tensile has
* fix for thread safety of solution lookup and assembly module storage
* hgemm implemented in assembly

tensile_tag update

---

Jenkinsfile

Machines jenkins-rocm-1 and jenkins-rocm-2 have ROCm 1.6.4 and the docker container is for ROCm 1.7.1. With the ROCm version mismatch tests are failing. Reomve Jenkins testing on these machines.

get 1.6.4 rocm-terminal for ROCm 1.6.4 Jenkins machines

---

library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_SB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Ailk_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Ailk_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Ailk_Bljk_SB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Alik_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Alik_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Alik_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Alik_Bljk_SB.yaml

resolves #___
-  Add Device 687f (alongside 6863) to all 24 vega10 yaml files.
Tests run:
- pre-checkin tests were run and passed on Vega 64

add Vega 64 support

---

library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_SB.yaml

These sizes generally use higher unroll to reduce bank conflict penalty.

add MIOpen sizes for TN with k high multiple of 2

---

Jenkinsfile

jenkins ci machines have been updated to ROCm 1.7.1. Update CI files so they work with ROCm 1.7.1

change for machine update to ROCm1.7.1

---

library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_SB.yaml

Changes to vega10_Cijk_Ailk_Bljk_SB are from adding the following exact sizes for the NN sgemm on vega10.
- ProblemSizes:
+          - Exact: [ 256, 193600, 1, 64 ]
+          - Exact: [ 64, 193600, 1, 64 ]
+          - Exact: [ 64, 193600, 1, 256 ]
+          - Exact: [ 512, 50176, 1, 128 ]
+          - Exact: [ 128, 50176, 1, 512 ]
+          - Exact: [ 256, 12544, 1, 1024 ]
+          - Exact: [ 1024, 12544, 1, 256 ]
+          - Exact: [ 2048, 3136, 1, 512 ]
+          - Exact: [ 512, 3136, 1, 2048 ]

rocBLAS .yaml file with some new resnet50 exact sizes

---

library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_SB.yaml

The modified file vega10_Cijk_Ailk_Bljk_SB.yaml is from adding the following gemm NN Exact sizes to Tensile file rocblas_sgemm_asm_full.yaml. Note that all the added Exact sizes have batch count of 64.
- Exact: [  196,  256, 64, 1024 ]
- Exact: [  784,  512, 64,  128 ]
- Exact: [   49,  512, 64, 2048 ]
- Exact: [  196, 1024, 64,  256 ]
- Exact: [   49, 2048, 64,  512 ]
- Exact: [ 3025,  256, 64,   64 ]
- Exact: [ 3025,   64, 64,   64 ]

add batch sizes to vega10 NN .yaml file

---

clients/gtest/set_get_matrix_gtest.cpp
clients/include/testing_set_get_matrix.hpp
clients/include/utility.h
library/src/rocblas_auxiliary.cpp

use size_t in place of int for number of bytes to copy in hipMemcpy called from rocblas_set_matrix and rocblas_get_matrix. This is required for double matrix of size 16700 x 16700 and other large matrices of byte size larger than can fit into int data type.

set,get_matrix use size_t for bytes_to_copy

---

clients/gtest/set_get_matrix_gtest.cpp

add large size that require number_of_bytes_allocated is size_t not int in rocblas_set_matrix and rocblas_get_matrix.

add size_t sizes to set_get_matrix_gtest

---

Jenkinsfile
clients/include/testing_gemm_strided_batched.hpp
clients/include/utility.h
clients/samples/example_openmp.cpp
clients/samples/example_scal_template.cpp
clients/samples/example_sgemm.cpp
clients/samples/example_sgemm_strided_batched.cpp
clients/samples/example_sscal.cpp
library/src/include/logging.h
library/src/utility.cpp

Clang Tot Upgrade has lint type errors. Adding include files to aim to remove errors

lint errors in ctu and swdev-153306

---

install.sh

Too many internal developers ran into our `yum -y update` forcing its way into upgrading their CentOS 7.4 to 7.5 - without even asking for permission.  This has the unfortunate consequence of breaking our own rocm-dkms drivers, in particular amdgpu.  On Ubuntu, `apt update` is needed to refresh the repo database.  On CentOS/Fedora, there is no need to do so.

Remove unnecessary yum -y update

---

clients/benchmarks/client.cpp
clients/common/arg_check.cpp
clients/common/norm.cpp
clients/common/unit.cpp
clients/gtest/gemm_strided_batched_gtest.cpp
clients/include/arg_check.h
clients/include/norm.h
clients/include/testing_gemm_strided_batched.hpp
clients/include/testing_logging.hpp
clients/include/unit.h
clients/include/utility.h
library/src/blas3/Tensile/gemm.cpp

rocblas_Xgemm_strided_batched tests modifications for stride_a==0 || stride_b==0. The following needed modifications:
* norm_check_general
* unit_check_general
* rocblas_init
Small changes were also needed in tests to allow for stride_a==0 || stride_b==0 .

rocblas_strided_batched tests correction for stride_a==0

---

library/src/blas1/rocblas_amax.cpp
library/src/blas1/rocblas_amin.cpp
library/src/blas1/rocblas_asum.cpp
library/src/blas1/rocblas_axpy.cpp
library/src/blas1/rocblas_copy.cpp
library/src/blas1/rocblas_dot.cpp
library/src/blas1/rocblas_nrm2.cpp
library/src/blas1/rocblas_scal.cpp
library/src/blas1/rocblas_swap.cpp

**resolves SWDEV 155606**
- compile errors arise from the Boolean conditional  (complex_float == 0).
- These errors started occurring after recent changes in HIP [ https://github.com/ROCm-Developer-Tools/HIP/pull/466]. 
- Comment out blas1 complex template functions to remove compile error. Complex is currently not implemented in rocBLAS, when it is implemented the complex template functions can be added back.

comment out blas1 complex template functions

---

library/src/blas3/Tensile/gemm.cpp

To avoid   n*ldc > std::numeric_limits<int>::max() chunk gemm in the n dimension.
Note that the following variables can be changed:
* int_limit
* chunk_size_min
The code should keep  n*ldc  less than int_limit, and it is set to the biggest possible int. Maybe it should be set to the largest   unsigned_int   . 
Also, the   chunk_size_min   is arbitrary. It is to prevent an artificially small chunk_size

initial code: chunk n to avoid n*ldc > numeric_limits<int>max()

---

library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Ailk_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Ailk_Bljk_SB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Alik_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Alik_Bljk_SB.yaml

Add k based kernel selection to rocblas_sgemm_asm_lite.yaml to call sgemm source kernels for k<128. This is a workaround for incorrect results from assembly kernels for stride_a == 0 || stride_b == 0 when batch_count > 1 and k < 128. The source kernels give the correct result for these sizes. 
This pull request is only for sgemm .yaml files in  rocBLAS/library/src/blas3/Tensile/Logic/asm_lite. There will be additional pull requests for dgemm .yaml files in asm_lite, and for sgemm and dgemm files in asm_full.

sgemm asm_lite,  source for k<=128

---

library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_SB.yaml

Add k based kernel selection to rocblas_sgemm_asm_full.yaml to call sgemm source kernels for k<128. This is a workaround for incorrect results from assembly kernels for stride_a == 0 || stride_b == 0 when batch_count > 1 and k < 128. The source kernels give the correct result for these sizes.
This pull request is only for sgemm .yaml files in rocBLAS/library/src/blas3/Tensile/Logic/asm_full. There will be additional pull requests for dgemm .yaml files in asm_lite and asm_full. PR#294 was for sgemm in asm_lite.

sgemm asm_full, source for k<=128

---

clients/gtest/gemm_strided_batched_gtest.cpp
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_lite/vega10_Cijk_Alik_Bljk_DB.yaml

Add k based kernel selection to rocblas_dgemm_asm_lite.yaml to call dgemm source kernels for k<128. This is a workaround for incorrect results from assembly kernels for stride_a == 0 || stride_b == 0 when batch_count > 1 and k < 128. The source kernels give the correct result for these sizes.
This pull request is only for dgemm .yaml files in:
- rocBLAS/library/src/blas3/Tensile/Logic/asm_full
- rocBLAS/library/src/blas3/Tensile/Logic/asm_lite 
Pull requests #294 and #296 are for sgemm .yaml files.

dgemm asm_lite, source for k<=128

---

clients/gtest/gemm_gtest.cpp
clients/include/testing_gemm.hpp
clients/include/utility.h

- In testing_gem.hpp matrices were incorrectly initialized to have all values equal to 1. Change to initialize matrices with random values.
- Correct rocblas_half random values so they are in range (1,2,3) for positive values, and (-1,-2,-3) for negative values.
- Separate rocblas_half known failures for small and tiny matrices.

Correct gemm test matrix initialization

---

CMakeLists.txt
clients/include/testing_gemm.hpp
clients/include/utility.h
library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_HB.yaml

-  partial backport of Correct gemm test matrix initialization
-  logic using hgemm hip yaml update for VW=2 and VW=1 on Vega 20
-  logic using changes from Tensile PR#297 for Vega 20

partial backport of Correct gemm test matrix initialization; updated hip_lite & hgemm_asm_full logic

---

library/src/include/definitions.h

resolves build failure for hip-clang.
-  llvm_fma_v2f16 is a device function, therefore should be qualified with __device__

Add __device__ to llvm_fma_v2f16

---

library/src/blas3/trtri_batched.hpp

resolves build failure for hip-clang.
-  hip-clang checks kernel argument type when calling hipLaunchKernelGGL
-  There is type mismatch without const when this kernel is launched by hipLaunchKernelGGL
-

Add missing const qualifier for argument of trtri_kernel_batched

---

install.sh

Add option --hip-clang to install.sh
- this option will let CXX=hipcc 
- CMakeLists.txt will detect hipcc is actually hip-clang and proceed properly

Let install.sh support --hip-clang

---

CMakeLists.txt

Using the CXX compiler's version output, determine whether the CXX compiler is HIP-clang, HCC or NVCC.

Check which CXX Compiler is enabled

---

clients/benchmarks/CMakeLists.txt
clients/gtest/CMakeLists.txt
clients/samples/CMakeLists.txt
library/CMakeLists.txt

resolves build failure of clients for hip-clang
-  need -mf16c for f16c intrinsic
-  need -lpthread -lm for rocblas_test

Change client cmake files to support hip-clang

---

clients/include/testing_gemm.hpp

Correct output from gemm-bench to give correct csv column names. Previous output had Gflops(us) and it should be Gflops,us

correct column names in gemm-bench output

---

CMakeLists.txt
clients/include/testing_gemm.hpp
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_HB.yaml

-  disable PreciseBoundsCheck for all Vega 10 & 20 HB YAML files
-  (amcamd) correct column names in gemm-bench output

disable PreciseBoundsCheck for all Vega 10 & 20 HB YAML files

---

clients/gtest/CMakeLists.txt
clients/gtest/gemm_ex_gtest.cpp
clients/include/testing_gemm_ex.hpp
clients/include/testing_logging.hpp
clients/include/utility.h
library/include/rocblas-functions.h
library/include/rocblas-types.h
library/src/CMakeLists.txt
library/src/blas_ex/rocblas_gemm_ex.cpp

Initial code for mixed precision gemm_ex
This code only supports the cases where all precision is half, float, or double. These fall back to calling the rocblas functions rocblas_hgemm, rocblas_sgemm, and rocblas_dgemm. It will be extended to support mixed precision gemm.
The pull request includes test code with limited testing.

initial gemm_ex

---

clients/include/testing_logging.hpp
library/src/handle.cpp
library/src/include/logging.h

Logging had a newline at the beginning of a line, not at the end of a line. This results in incorrect newline when rocBLAS logging is streamed to std::err and mixed with other logging.
The main change in this pull request is in the file library/src/include/logging.h. Many lines in the file clients/include/testing_logging.hpp are to change the reference output.

move newline from front to end of logging trace line

---

Jenkinsfile
clients/gtest/blas1_gtest.cpp
clients/gtest/geam_gtest.cpp
clients/gtest/gemm_ex_gtest.cpp
clients/gtest/gemm_gtest.cpp
clients/gtest/gemm_strided_batched_gtest.cpp
clients/gtest/gemv_gtest.cpp
clients/gtest/ger_gtest.cpp
clients/gtest/logging_mode_gtest.cpp
clients/gtest/set_get_matrix_gtest.cpp
clients/gtest/set_get_pointer_mode_gtest.cpp
clients/gtest/set_get_vector_gtest.cpp
clients/gtest/syr_gtest.cpp
clients/gtest/trsm_gtest.cpp
clients/include/testing_gemm_sweep.hpp

Add tests to sweep over a wider range of  sizes for gemm
Add Google-test  labels quick, pre_checkin, nightly with test times:
- quick: 35 sec
- quick + pre-checkin:  9min 41 sec
- nightly: 43 min

rename tests quick, pre_checkin, nightly, add sweep tests for gemm

---

library/src/blas3/Tensile/Logic/asm_miopen/hip_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_miopen/hip_Cijk_Ailk_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_miopen/hip_Cijk_Alik_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_miopen/hip_Cijk_Alik_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_miopen/vega10_Cijk_Ailk_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_miopen/vega10_Cijk_Ailk_Bljk_SB.yaml
library/src/blas3/Tensile/Logic/asm_miopen/vega10_Cijk_Alik_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_miopen/vega10_Cijk_Alik_Bljk_SB.yaml

Migrating the current fallback HGEMM logic files from asm_full to asm_miopen resolves the 300+ HGEMM rocblas-test failures when building with -l asm_miopen.

migrate asm_full/hip*HB.yaml to asm_miopen; disable PreciseBoundsCheck for asm_miopen/*vega10*SB.yaml

---

clients/include/testing_gemm_ex.hpp
clients/include/testing_logging.hpp
library/include/rocblas-functions.h
library/src/blas_ex/rocblas_gemm_ex.cpp

With this change the function gemm_ex can be called to calculate the workspace. The user would then allocate the workspace and call gemm_ex again to carry out the calculation.

make workspace_size argument an in/out pointer not an in scalar

---

clients/gtest/gemm_gtest.cpp

Add fixed_bug to rocBLAS tests. This is for sizes with reported bugs that have been fixed.

add fixed_bug test for SWDEV-163346

---

clients/benchmarks/client.cpp
clients/common/norm.cpp
clients/include/testing_gemm_strided_batched.hpp
clients/include/utility.h

-  In clients/common/norm.cpp, correct memory allocation, and switch to using half_to_float()
-  In clients/include/testing_gemm_strided_batched.hpp, declare rocblas_error as double, and print alpha and beta as float for half; clang-format changes
-  In clients/include/utility.h, add stride_d
-  In clients/benchmarks/client.cpp, correct typo stride_c -> stride_d

gemm_strided_batched rocblas-bench bug fixes

---

library/src/blas3/Tensile/gemm.cpp

To solve the performance degrade in Dgemm (C += A*B ) caused by unnecessary chunking.
With either matrix A or B, chunking can only be done with the other dimension when the Leading Dimension is the same as the Summation Dimension, more specifically:
Matrix A can only be chunked along the "m" dimension when trans_a is rocblas_operation_transpose.
Matrix B can only be chunked along the "n" dimension when trans_b is rocblas_operation_none.

Fix incorrect chunking in CALL_TENSILE of gemm.cpp

---

clients/gtest/gemm_gtest.cpp
clients/gtest/gemm_strided_batched_ex_gtest.cpp

- remove one hgemm test that has known failure due to acceptable IEEE overflow
- move resnet50 known_but to nightly
- add back gemm_ex known bug

move known_bug to nightly

---

clients/include/testing_gemm_ex.hpp

Additional check is required for K >= 2 . I do not think we have tests with K ==1 and N !=1 || M != 1

need extra check for K >= 2

---

library/src/blas3/Tensile/gemm.cpp

If GSU splits the k dimension these should be warnings not errors

ERROR 2 WARNING whtn lda*k or ldb*k exceeds address limit

---

CMakeLists.txt

It's possible for there not to have a CMAKE_CXX_COMPILER. We will run into REGEX errors if the number of arguments don't exceed 5.
-  Add guard to check CMAKE_CXX_COMPILER is either hcc or hipcc
-  This will prevent having an empty arguments going into string(REGEX MATCH

Guard the CXX Compiler check if not set

---

clients/include/testing_gemm.hpp
clients/include/testing_gemm_ex.hpp
clients/include/testing_gemm_strided_batched_ex.hpp

-  Change timing of gemm_ex and gemm_strided_batched_ex to assume matrices D and C are the same
-  Display transA and transB as N/T as opposed to 111/112
-  Print alpha and beta their actual values for half type
-  Correct Gflops calculation to include batch_count for gemm_strided_batched_ex

testing_gemm{,*_ex} bug fixes

---

clients/common/utility.cpp
library/src/CMakeLists.txt
library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bjlk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bljk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bjlk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bljk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bjlk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bljk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bjlk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bljk_4xi8BH.yaml

- add YAML files for int8 gemm
- add -mcpu-gfx906 compile flag for Tensile code that uses __builtin_amdgcn_sdot4
- fix clang-format error from previous pull request

add int8 YAML files

---

clients/benchmarks/client.cpp
clients/include/testing_gemm_ex.hpp
clients/include/testing_gemm_strided_batched_ex.hpp
clients/include/testing_logging.hpp
clients/include/utility.h
library/include/rocblas-functions.h
library/src/blas_ex/rocblas_gemm_ex.cpp

For gemm_ex and gemm_strided_batched_ex change solution_index from uint32_t to int32_t. 
This will enable setting positive values 0,1,2,3,... for solution indices, and negative value like -1 to use the default

change gemm_ex solution_index from uint32_t to int32_t

---

clients/common/cblas_interface.cpp
clients/gtest/gemm_ex_gtest.cpp
clients/include/testing_gemm_ex.hpp
clients/include/utility.h
library/src/blas_ex/rocblas_gemm_ex.cpp

-  Replaced Int8 testing cblas unpacking code with rocblas packing code. Matricies sent to compare should now be in the expected format, with overflow issues for larger sizes fixed.
-  Force a test fail if an unexpected error code is returned. 
-  Added invalid Int8 specific matrix sizes to expected errors.

Changed Int8 tests to properly pack the matrix to the expected format

---

clients/CMakeLists.txt

HIP may be installed to a directory other than /opt/rocm/hip.
Application should respect CMAKE_PREFIX_PATH and try to look for package from there first.
Unless it is not set then look in /opt/rocm.
resolves build failure with hip-clang and HIP/VDI runtime.
-  find HIP at CMAKE_PREFIX_PATH
-  
-

Fix HIP package directory for HIP/VDI runtime

---

CMakeLists.txt
clients/benchmarks/client.cpp
clients/gtest/rocblas_gtest_main.cpp
library/include/rocblas-functions.h
library/src/CMakeLists.txt
library/src/buildinfo.cpp

- Added API call for rocblas library version. 
- Added --version option to rocblas-bench
- Added printing of library version to rocblas-test by default

Library Versioning Enabled for rocblas-bench and rocblas-test

---

CMakeLists.txt
Jenkinsfile
cmake/version.cmake
library/include/rocblas-version.h.in
library/src/buildinfo.cpp

-  Removed git commit ID from libocblas.so filename.-  
-  Fixed dirty commit IDs on Jenkins

Removed git commit ID from librocblas.so filename. Fixed dirty commit IDs on Jenkins

---

library/src/blas1/rocblas_axpy.cpp
library/src/include/definitions.h

- ROCm 2.0 has include file hip_fp16.h that defines half2
- change name in rocBLAS from half2 to rocblas_half2 
- rocBLAS was using half before it was a data-type in ROCm

ROCM2.0 fix: half2 to rocblas_half2

---

clients/gtest/blas1_gtest.yaml

Random IAMIN error very hard to track down. Does not happen with IAMAX. Might be a compiler bug or uninitialized data.

Temporarily disable IAMIN tests until random error is fixed

---

library/src/blas3/rocblas_trsm.cpp
library/src/blas3/trtri_trsm.hpp

(Resubmission of PR#440 with conflicts resolved.)
contributes towards #172044
Send smaller sizes in to the trtri kernel
Remove packedB to avoid unnecessary memory allocation
Remove unnecessary hipMemsetAsync on X variable

TRSM optimizations - reduce copies and smaller trtri kernel sizes

---

clients/benchmarks/client.cpp
clients/include/rocblas_arguments.hpp
clients/include/rocblas_init.hpp
clients/include/testing_gemm.hpp

- Add option to initialize gemm matrices with trig functions sin and cos.
- This is an alternative to initializing with random integers in [1,10] and alternating sign random integers in  [1,10]
- This is only useful for rocblas-bench performance measurement, and it is cannot be used for correctness tests.

initialize matrices with trig functions sin and cos

---

clients/common/rocblas_gentest.py
clients/include/rocblas_arguments.hpp
clients/include/rocblas_common.yaml
clients/include/rocblas_data.hpp

PR #458 broke tests because they were read in as binary and interpreted as binary data which, because of the `rocblas_initialize` entry added to the `Arguments` `struct`, were read in garbled, and thus rarely matched test criteria, reducing the number of tests.
- Add the `rocblas_initialize` definition to the YAML file
- Enhance `rocblas_gentest.py` to handle `enum` `Arguments` besides `rocblas_datatype`
- Add code to detect a mismatch between input data and output data, giving a clear error message about the data being misformatted, and how to fix it

Fix regression in PR#458 caused by change in Arguments data structure

---

library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_HBH.yaml

This is a fix which updates the vega20 HBH logic files which, by removing the VectorWidth=2 assertions from the Source configurations prevents the faulty kernel selection which is what we have been seeing in these 96 failures.
note as of this submission I have only verified that this fix works for one of the failing test cases.   
-  
-  
-

fix for 96 test failures

---

library/src/blas3/trtri_device.h
library/src/blas3/trtri_trsm.hpp

contributes towards #172044
- New custom trtri kernel used for TRSM runs 256 threads in a block to work on two 16x16 diagonal tiles at the same time.
- After completing the inverses the results are used within the kernel to preform 2 gemms. This was previously done outside of the kernel.

TRSM Optimization: Custom Trtri Kernel

---

library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_DB.yaml
scripts/performance/dgemm_hpl_list2.sh
scripts/performance/dgemm_hpl_list3.sh
scripts/performance/dgemm_hpl_list4.sh

+ Latest gfx906 DGEMM NT tuning for k={256,384},m=n and k={256,384},n={2048,3072}.
+ Some gfx906 DGEMM NN+NT tunning for DTRSM.
+ 3 new scripts to cover the new sizes.
Full rocblas-test passed on gfx906.  No change here is applicable to gfx900.

DGEMM NT tuning plus some new scripts

---

library/src/blas1/reduction.h
library/src/blas1/rocblas_amax_amin.h

resolves #457 ___
Instead of using `T{}` to generate default values for a class, use variable templates specialized for classes. This avoids needing to define non-trivial default constructors, which are not allowed in `__shared__` variables. No further initialization of `__shared__` variables is required, because the original code did not depend on it.

Fix compilation of IAMAX, IAMIN

---

library/src/blas2/rocblas_trsv.cpp
library/src/handle.cpp
library/src/include/handle.h

resolves #473
Copy from host to device memory instead of relying on dynamic initialization of `__device__` variables.
(Might be using some undocumented extension of `__device__` function-level `static` variables, but seems to work.)

Fix TRSV compilation

---

clients/gtest/known_bugs.yaml
clients/include/rocblas_random.hpp

this fixes the issue with the 9 known bugs.
The change was to change the range in the random number initialization to prevent overflow.
All the rocblas-test's were verified to pass on vega10.
-  
-  
-

fix for 9 known bugs

---

library/include/rocblas-functions.h

- add supported types table for gemm_ex and gemm_strided_batched_ex
- add information on restrictions for gemm_ex and gemm_strided_batched_ex for i8_r/i32_r
- k must be a multiple of 4
- matrices A and B must have each 4 consecutive values in the k dimension packed or contiguous

add restrictions in Doxygen documentation for rocblas_gemm_ex and rocblas_strided_batched_ex

---

scripts/performance/i8_r_gemm_ex_MIOpen.sh
scripts/performance/i8_r_gemm_strided_batched_ex_MIOpen.sh

- add scripts to compare i8_r/i32_r gemm_ex and f32_r gemm_ex
- sizes are from MIOpen
- the values of k for i8_r/i32_r are 4 times the k values for f32_r
- the time should be the same for the i8_r/i32_r gemm_ex versus the f32_r gemm_ex

i8_r/i32_r sizes from MIOpen

---

library/include/rocblas-functions.h

- Sphinx omits Doxygen tables.
- Replace table for supported types and restrictions with bulleted lists

convert table to bulleted list

---

clients/benchmarks/CMakeLists.txt
clients/benchmarks/client.cpp
clients/common/rocblas_parse_data.cpp
clients/gtest/CMakeLists.txt
clients/gtest/rocblas_gtest_main.cpp
clients/include/near.hpp
clients/include/rocblas_data.hpp
clients/include/rocblas_parse_data.hpp
clients/include/testing_trtri.hpp
clients/include/unit.hpp

`--data` and `--yaml` options for rocblas-test and rocblas-bench allow binary or YAML input data. More work is required to make free-form YAML parse correctly. This implements the command-line interface.

initial implementation of --data and --yaml options

---

Jenkinsfile
clients/gtest/rocblas_gtest_main.cpp

- Jenkinsfile sets environment variable GTEST_LISTNER to "NO_PASS_LINE_IN_LOG" to omit pass line from log. This reduces the size of the log file. 
- If envirnoment variable GTEST_LISTNER is not set to "NO_PASS_LINE_IN_LOG" then gtest will output pass and fail lines.

env variable GTEST_LISTENER for NO_PASS_LINE_IN_LOG

---

clients/benchmarks/client.cpp
clients/include/rocblas_arguments.hpp
clients/include/rocblas_datatype2string.hpp
clients/include/rocblas_test.hpp
clients/include/test_cleanup.hpp
clients/include/testing_asum.hpp
clients/include/testing_nrm2.hpp
library/src/include/utility.h

Allow single-precision letters or longer type names to be used with `rocblas-bench` anywhere types are expected on the command-line.
Remove `precision` as being a main variable in `rocblas-bench`, and makes it simply a default value for `a_type`, `b_type`, `c_type`, `d_type`, `compute_type`, so that after those are set, `precision` is forgotten downstream. That is how the YAML-driven tests work already, since the `Arguments` data structure doesn't use `precision`.
Simplify error-handling in `rocblas-bench` by using exceptions.
Refactor `rocblas-bench` to be much simpler using templates, getting rid of all the precision testing in the body of the code, and relying instead of the type dispatch mechanism.
Fix a couple of typos in type string conversion.

fix for precision specifiers

---

library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_DB.yaml

-  Re-tuned all DGEMM NT sizes with Tensile DataInitTypeBeta set to 2
-  More DGEMM NT sizes are tuned, including k=256,n=1792 and k=384,n=2688
-  For certain DGEMM NT sizes, take leading dimensions into account when tuning

DGEMM NT tuning & re-tuning

---

CMakeLists.txt

Use Tensile commit 94a44425095b6abb3b9f064d2082d2b18716c243 to build rocBLAS.

restore support of rocBLAS build without an AMD GPU

---

cmake/virtualenv.cmake

resolves #499 
A minor tweak to the relevant file where it first tries to find a binary explicitly named `python2` and will use that if it does, if not, then it makes the check already in upstream.
This fixes the build for the following scenario:
```
ls -l /usr/bin/python*
python3
python2
python -> python3
```
Which happens in newer distros (in my case, Arch)

Fixed an issue where the build woulf fail if `/usr/bin/python` was python3

---

clients/benchmarks/CMakeLists.txt
clients/gtest/CMakeLists.txt
clients/samples/CMakeLists.txt

resolves SWDEV-182629
- need to add include directory   /opt/rocm/hsa/include for file hsa/hsa.h

add /opt/rocm/hsa/include to target_include_directories

---

library/src/CMakeLists.txt

- Tests show this flag speeds up the link time considerably
- one caveat is that a kernel cannot call a function defined in another .cpp file

to speed up link add flag -fno-gpu-rdc

---

library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_DB.yaml

Passed full rocblas-test on both Vega 10 and Vega 20 overnight.

DGEMM NT tuning for Feb 24 sizes with Raman's 2 6x4 replacement kernels

---

library/src/CMakeLists.txt
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_SB.yaml

- Add Radeon VII to all vega20 logic files.
- Make sure whenever -fno-gpu-rdc is used, --amdgpu-target= options are explicitly specified to have the appropriate fat code objects generated; it also ensures that rocBLAS can be built when GPU isn't present, such as in docker.

add Radeon VII

---

clients/benchmarks/client.cpp
clients/include/rocblas_datatype2string.hpp
clients/include/rocblas_init.hpp
clients/include/rocblas_random.hpp
clients/include/testing_gemm.hpp

HPL initializes data distribution across [-0.5, 0.5]. This change adds a new initialization parameter to rocblas-bench for HPL-like input.

Add HPL-like initialization to rocblas-bench

---

library/src/blas2/rocblas_gemv.cpp

resolves swdev-178779
- make gemv comply with reference implementation by not allowing NaN in y vector to propagate when beta = 0

avoid NaN propagation in gemv when beta==0

---

library/src/CMakeLists.txt

- ROCm 2.3 changes from hipHccModuleLaunchKernel to hipExtModuleLaunchKernel. 
- Deprecate warning messages untill the following commit is merged: 
https://github.com/amcamd/Tensile/commit/f4809158d82a11eac3a03bf6413cbecad9bd4a56  
- This commit changes to hipExtModuleLaunchKernel, but it will only work on ROCm2.3 or later.

no deprecation warnings for hipHccModuleLaunchKernel

---

clients/include/near.hpp
clients/include/rocblas.hpp
clients/include/rocblas_math.hpp
clients/include/testing_logging.hpp
library/src/blas1/rocblas_amax_amin.h
library/src/blas1/rocblas_asum.cpp
library/src/blas1/rocblas_axpy.cpp
library/src/blas1/rocblas_copy.cpp
library/src/blas1/rocblas_dot.cpp
library/src/blas1/rocblas_nrm2.cpp
library/src/blas1/rocblas_scal.cpp
library/src/blas1/rocblas_swap.cpp
library/src/blas2/rocblas_gemv.cpp
library/src/blas2/rocblas_ger.cpp
library/src/blas2/rocblas_syr.cpp
library/src/blas2/rocblas_trsv.cpp
library/src/blas3/Tensile/gemm.cpp
library/src/blas3/rocblas_geam.cpp
library/src/blas3/rocblas_trmm.cpp
library/src/blas3/rocblas_trsm.cpp
library/src/blas3/rocblas_trtri_batched.cpp
library/src/include/utility.h

Resolves: SWDEV-188303
In [DR2387](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1359r0.html#2387), it was recently decided that unlike regular `const`-qualified variables, `const`-qualified **_variable templates_** do not have internal linkage by default.
Most compilers up to now have made `const`-qualified variable templates have internal linkage by default, all the way back to C++14. The standard was unclear.
This change declares _all_ `const`-qualified variable templates in rocBLAS as `static`.
[Recent changes to clang for DR2387](https://github.com/llvm/llvm-project/search?q=DR2387&type=Commits), which change the default linkage of `const`-qualified variable templates from internal to external.
[Detailed history / context of the …

Following DR2387, explicitly declare const[expr] variable templates static

---

library/src/buildinfo.cpp

Current code unnecessarily uses `std::string` while plain C-style `char` array is sufficient (`std::string` requires allocation and deallocation from the heap, while C-style `char` array can be stored in `.text` as read-only memory).
Current code calls `strcpy` before checking whether the destination is `NULL`, which can cause crash instead of detecting the `NULL`. Also, status code should be `rocblas_status_invalid_pointer` instead of `rocblas_status_internal_error`.
Current code is overly complicated with respect to copying the string to the destination, copying it twice.
The new code checks whether destination is large enough, and if it is, calls `memcpy` to copy the known-length string (including the trailing `'\0'`); otherwise, it returns `rocblas_status_invalid_size`.

Simplify and fix error handling of version string function

---

library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bjlk_BBH.yaml
library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Ailk_Bljk_BBH.yaml
library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bjlk_BBH.yaml
library/src/blas3/Tensile/Logic/asm_full/hip_Cijk_Alik_Bljk_BBH.yaml
library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bjlk_BBH.yaml
library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Ailk_Bljk_BBH.yaml
library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bjlk_BBH.yaml
library/src/blas3/Tensile/Logic/hip_lite/hip_Cijk_Alik_Bljk_BBH.yaml

- Add initial tuning yaml file for bfloat16.
- This should provide functionality, and it will need to be tuned later

add yaml files for bfloat16 hip kernels

---

library/src/blas2/gemv.hpp
library/src/blas2/rocblas_trsv.cpp
library/src/blas3/rocblas_trsm.cpp
library/src/handle.cpp
library/src/include/handle.h
library/src/include/rocblas_trsm.hpp
library/src/include/rocblas_trsv.hpp

1. use gemv to implement trsv
2. add trsv_ex function
resolves #___
-  some of our users didn't accept to use trsm to implement trsv function.
-  We implement trsv function by using gemv function. We are reference to trsm function and replace gemm by gemv to achieve trsv function which has better performance.
-  We also implement trsv_ex and trsv_ex testcase, all implementation are reference to trsm implementation.

trsv implementation

---

clients/include/rocblas_random.hpp
library/include/rocblas_bfloat16.h

-  Uses bitwise operations to optimize conversion from `float` to `rocblas_bfloat16`, correctly handling rounding, `NaN` and `Inf` (see inline comments).
- Uses "type punning" between `float` and `uint32_t` instead of between `float` and `uint16_t [2]`, to simplify operations and remove dependence on endianness.
- Makes `rocblas_bfloat16.h` compatible with the C language, by only defining `typedef struct { uint16_t data; } rocblas_bfloat16;` when the C language is used.
- Uses `static_assert` to ensure that C++ definition of `rocblas_bfloat16` is compatible with the C language.
- Changes preincrement operator function to return lvalue references rather than values.
- Adds predecrement and postdecrement operators.
- Adds unary `+` and unary `-` operators.
- …

Simplify and tune rocblas_bfloat16.h

---

clients/samples/example_bf16_r_gemm_ex.cpp

- correct pointer declaration changing from float* to rocblas_bfloat16*

fix pointer declaration in bfloat16 sample

---

docs/run_doxygen.sh
docs/source/api.rst
library/include/rocblas-functions.h
library/include/rocblas_bfloat16.h

- add bfloat16, gemm_ex, and gemm_strided_batched_ex content to ReadTheDocs / Sphinx / Breath / Doxygen documentation.
- It will likely be necessary to edit these changes after documentation is shown here: https://rocblas.readthedocs.io/en/latest/api.html#rocblas-int

add bfloat16 documentation

---

CMakeLists.txt
clients/benchmarks/CMakeLists.txt
clients/gtest/CMakeLists.txt
clients/include/rocblas_math.hpp
clients/samples/CMakeLists.txt
library/include/rocblas_bfloat16.h

resolves compilation with HIP/Clang
-  Include HIP header
-  Add necessary __device__/__host__ attributes.
-  Remove default initializer so that `bfloat16` could be used with `__share__`, which forbids any initializer.

[hip] Add HIP support for `bfloat16`.

---

CMakeLists.txt
clients/CMakeLists.txt

- set( CMAKE_CXX_STANDARD 14 ) in CMakeLists.txt because rocblas_bfloat16.h uses C++14
- this will be passed to clients/CMakeLists.txt, so the setting in clients/CMakeLists.txt becomes redundant and can be removed
- without this setting, there are compiler warnings

use c++14 compile flag for rocblas_bfloat16.h

---

CMakeLists.txt

When building rocBLAS with HIP-Clang, -D__HIP_HCC_COMPAT_MODE__=1 is needed to deal with Tensile-generated calls hc_get_group_id, hc_get_num_groups, hc_get_workitem_id and hc_get_workitem_absolute_id.
Full rocblas-test passed on gfx900 and gfx906 as well as a hip-clang build in docker.

add HIP-Clang support

---

clients/include/testing_gemm_ex.hpp

- modify bfloat16 test so that it will fail if IEEE16 bit arithmetic is used, and it will pass if IEEE32 bit arithmetic is used
- Full rocBLAS tests pass on gfx900 and gfx906

add bfloat16 test that will fail for ieee16 and pass for ieee32

---

library/include/rocblas_bfloat16.h

- in rocblas_bfloat16.h include hip/hip_runtime_api.h in place of hip/hip_runtime.h
- this enables compiling with gcc

HotFix: include hip_runtime_api.h in place of hip_runtime.h

---

library/include/rocblas_bfloat16.h

- remove C++14 from external include file rocblas_bfloat16.h

remove C++14 constexpr for C++11 compatibility

---

.clang-format
library/src/blas1/reduction.h

- Additional options are now available in clang-format, and they need to be applied to Jenkins after I upgraded CI from rocm2.4 to rocm2.5

New clang-format for rocm2.5

---

Jenkinsfile
docker/dockerfile-build-centos
docker/dockerfile-install-centos

-	Idea is to run a CentOS instance of rocBLAS in CI
-	CentOS7 image is more barebones than the Ubuntu base image, so additional packages need to be installed to enable CentOS support
-	Some CentOS/rpm packages have slightly different names than Ubuntu/debian packages 
-	cmake3 must be specified for centOS7, as the default cmake is cmake2. 
-	sudo privileges for running tests must be added to the Jenkinsfile to run in CentOS w/o getting a permissions issue (not sure why this is happening, group and user permissions do appear to be the same as Ubuntu)
CentOS support in general:
-	All existing Jenkins nodes can run CentOS jobs because it's being ran in a docker container
-	Currently gfx900 is set to test CentOS7 base image, but this can be changed pretty easily
- …

Adding CentOS CI support

---

library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Ailk_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Ailk_Bljk_SB.yaml
library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Alik_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Alik_Bljk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bljk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_4xi8BH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_SB.yaml

Resolves SWDEV-190051
- when /usr/share/misc/pci.ids is missing on the system, Radeon VII presents itself as 'Device 66af', not 'Vega 20'.  This fix brings 'Device 66af' into the 'Vega 20' fold.

add 'Device 66af' for Radeon VII

---

.github/CONTRIBUTING.md

-  Change in documentation to use git ls-files instead of find

Use git ls-files instead of find for clang-format

---

library/src/blas2/rocblas_trsv.cpp
library/src/blas3/rocblas_trsm.cpp
library/src/include/handle.h

Fix allocator bug for when size = 0 is requested for one or more arrays.
Add one-time warning messages when degraded performance is encountered in TRSM or TRSV.
Add `total_size()` function for querying allocated memory's total size.

Fix allocator bug; add one-time warning messages about degraded performance

---

header_compilation_tests.sh
library/include/rocblas_bfloat16.h
library/src/CMakeLists.txt

Use a simpler method to ensure C/C++11/C++14 compatibility in `rocblas_bfloat16.h`.
Only if C++14 and HCC are detected enabled, does it include the `__device__` and `constexpr` code. Otherwise it uses a plain old C `struct`.
Fit a typo in the `struct`.
Parallelize the `header_compilation_tests.sh` header file validation script, reducing build times.

Fix typo and simplify compatibility logic in rocblas_bfloat16.h; parallelize header file checking

---

clients/benchmarks/client.cpp
clients/gtest/README.md
clients/include/rocblas_datatype2string.hpp

- bfloat16 tests are already part of rocblas-test
- small changes are needed to add bfloat16 to rocblas-bench

add bf16 to rocblas-bench

---

library/src/CMakeLists.txt

Fixing the library version to stop using the package version. This is requested by Radha and is blocker for 2.7.
Please take a look at https://github.com/RadeonOpenCompute/rocm-cmake/pull/15/files
This will fix most of the CI problems.

Swithing to rocm-cmake rocm_set_soversion

---

library/include/rocblas-complex-types.h
library/include/rocblas_bfloat16.h

resolves SWDEV-198354
- Need to check hip-clang as well to include the full definition of bfloat16 & complex

Check hip-clang as well.

---

docker/dockerfile-build-centos
docker/dockerfile-build-fedora
docker/dockerfile-build-ubuntu-rock
install.sh

rocBLAS currently fails to compile if the user does not have the zlib package installed on their machine. This may cause problems with CI as the CentOS image does not have zlib-devel installed by default

Add zlib package to install script and dockerfiles

---

CMakeLists.txt
Jenkinsfile
clients/CMakeLists.txt
clients/benchmarks/CMakeLists.txt
clients/gtest/CMakeLists.txt
clients/samples/CMakeLists.txt
docker/dockerfile-build-centos
docker/dockerfile-build-ubuntu-rock
install.sh
library/CMakeLists.txt
library/src/CMakeLists.txt

- rocBLAS develop branch is failing right now as it cannot find OpenMP 
- This PR adds libomp-dev for Ubuntu and libgomp for CentOS
- Also adds llvm6.0 for Ubuntu and llvm7.0 for CentOS
- There are some additional issues with OpenMP/pthreads that occur on CentOS, and some fixes are added in some of the CMake files to fix that 
- I had similar issues with PR #621 and am applying similar changes to the develop branch . 
- Passed CI with Ubuntu jobs

Adding missing packages to rocBLAS cmake files, dockerfiles, and install script

---

header_compilation_tests.sh

Uses \n instead of \0 in output to xargs. Compare with two previous versions, to see the real changes.
I'm still not sure of the root cause of the previous failure, which depends somehow on ROCm version. There is important logic in this change which prevents hangs during rebuilds and which prints the header files causing errors, so simply reverting to the earlier code is not safe.

Remove \0s from xargs input, to avoid corrupted characters

---

CMakeLists.txt

Pinning to stable version of Tensile to allow Paul Fultz's PR to merge. https://github.com/ROCmSoftwarePlatform/Tensile/pull/621 will break rocBLAS builds. This will allow us to merge the Tensile PR without causing Jenkins failures.

Pinning Tensile version to allow for stable Jenkins runs

---

install.sh

- CMakeLists.txt defines tensile_tag 
- rocBLAS uses tensile_tag to pull a specific branch/hash/tag of Tensile
- install.sh should call cmake with -Dtensile_tag not -Dtensile_branch so that it matches tensile_tag defined in CMakeLists.txt

change install.sh tensile_branch to tensile_tag to match CMakeLists.txt

---

CMakeLists.txt

- pull from Tensile hash that has cherry-picked into master from develop to get metadata for replacement kernels
- bump rocBLAS master branch version

pull Tensile with metadata for replacement kernels

---

library/include/rocblas_bfloat16.h
library/src/blas1/rocblas_rotg.cpp
library/src/blas1/rocblas_rotmg.cpp
library/src/include/utility.h

I will have to do build and test run manually.
I'm not 100% sure this fixes it, but it should.

Fix rocblas_bfloat16 conversions and add a __device__ __host__ rocblas_abs() function

---

clients/benchmarks/CMakeLists.txt
clients/gtest/CMakeLists.txt
install.sh

I have added a flag to the install script to be able to choose between the blis and lapack cpu libraries.
- cpu_lib flag is set to blis by default. 
I believe I should update the wiki page to include information on this flag when building the client.

Adding flag to install script to choose cpu lib

---

header_compilation_tests.sh
library/src/CMakeLists.txt

resolves #664
Change `header_compilation_tests.sh` to use CMake variables and data extracted from files, instead of hard-coded paths.
I have verified that it works in a `/tmp` build directory instead of the standard rocBLAS build tree. Running `install.sh` and running `make` from `build/release` still run the header checks.
We are nearing code-complete and this will be merged into `master` (or the `staging` branch) shortly, which will add parallelism to the existing script on `master`, making it less annoying during builds.

Fix header file checks to not depend on hardcoded paths

---

library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Ailk_Bljk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_DB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_HBH.yaml
library/src/blas3/Tensile/Logic/asm_full/vega10_Cijk_Alik_Bljk_SB.yaml

Resolves #653 
In the long run, a more reliable way of identifying the hardware is needed (why not just go by gfx***?)

Add support for Vega 64

---

clients/include/testing_rotm.hpp

Fixes test failures when compiled with hipclang. Tested both hcc and hipclang builds.

Make rotm test use near check

---

Jenkinsfile

* Timeout unit was changed in the rocJenkins to minutes instead of hours. 
* rocBLAS will use default rocJenkins timeout.

Fixing timeout for rocBLAS

---

clients/benchmarks/CMakeLists.txt
clients/gtest/CMakeLists.txt

**hot fix for ROCm 2.9 Centos build**
- look for immintrin.h in two locations, or error out

set clang include directory, fix for centos build error

---

library/src/blas3/Tensile/Logic/asm_full/arcturus_Cijk_Alik_Bljk_BBH.yaml

Current solution selection logic excludes UseBeta=False kernels.  Need investigation.  In the meantime, UseBeta=True logic is restored.  4 gfx908 rocblas-test unit tests failed due to non-zero beta being tested.

Restore usebeta1 logic

---

clients/benchmarks/client.cpp
clients/common/rocblas_gentest.py
clients/gtest/blas1_gtest.cpp
clients/gtest/blas1_gtest.yaml
clients/include/rocblas.hpp
clients/include/rocblas_arguments.hpp
clients/include/rocblas_common.yaml
clients/include/rocblas_template.yaml
clients/include/testing_swap_batched.hpp
clients/include/testing_swap_strided_batched.hpp
library/include/rocblas-functions.h
library/src/CMakeLists.txt
library/src/blas1/rocblas_swap.cpp
library/src/blas1/rocblas_swap.hpp
library/src/blas1/rocblas_swap_batched.cpp
library/src/blas1/rocblas_swap_batched.hpp
library/src/blas1/rocblas_swap_strided_batched.cpp
library/src/blas1/rocblas_swap_strided_batched.hpp

This adds into blas1 the batched and strided_batched for swap.  Refactors non batched swap to follow new coding pattern (impl and template).   It defers the merging of the batched and strided_batched kernels until final pattern agreed upon but already shares the simple computation kernel code.
Example combined test times for all 3 cases on Vega20:
372 tests from 6 test cases ran. (31937 ms total)

Batched swap

---

clients/gtest/blas1_gtest.yaml

Summary of proposed changes for pre-checkin test failure:
Tests with large N for single precision accumulation functions got accidentally put in with a merge
Removes large N single precision pre-checkin tests on asum, nrm2 rather than increase tolerance, keeps all other data types with large N and still checks single precision in other tests

drops float precision for large N asum,nrm2

---

deps/external-lapack.cmake

resolves SWDEV-203325
Added in a workaround flag for a known bug for Gfortran versions 7,8,9. Details at the link below:
https://developer.r-project.org/Blog/public/2019/05/15/gfortran-issues-with-lapack/index.html
Would like to see if there is any timing impact on CI with this flag enabled.

Adding Workaround flag for fortran bug

---

clients/gtest/known_bugs.yaml

```
rocBLAS version: 2.9.0.1588-c909d79
Query device success: there are 1 devices
-------------------------------------------------------------------------------
Device ID 0 : Vega 20
with 34.3 GB memory, clock rate 1701MHz @ computing capability 3.0
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 64
-------------------------------------------------------------------------------
Note: Google Test filter = *known_bug*
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from known_bug/gemm_ex
[ RUN      ] known_bug/gemm_ex.blas3/bf16_rbf16_rbf16_rbf16_rf32_r_CN_1024_1024_1024_5_1024_1024_0_1024_1024
[       OK ] known_bug/gemm_ex.blas3/bf16_rbf16_rbf16_rbf16_rf32_r_CN_1024_1024_1024_5_1024_1024_ …
```

Add known bugs for BF16 cases

---

.clang-format

Rocm2.8 has a new version of clang format that adds a space between the brackets of constructors that do not have a body
ex. class A(int a, double b) {} -> class A(int a, double b) { }
I've added a one-line change to clang-format that ignores this regression, and allows our CI to pass the format check. I'll add this to all projects

removed space in empty block

---

library/src/blas1/rocblas_swap_batched.hpp
library/src/blas1/rocblas_swap_strided_batched.hpp

Wasiq pointed out the negative increment handling offset is constant across batches so pulled it out of the kernel for both batched variants via the offset/shift argument we already added for rocSOLVER.    So do we expect the negative shift being large and so should make offsets rocblas_stride or assume the += N*inc is still fine as int32.   I would lean toward making it a rocblas_stride to allow this optimization.

handle negative inc via pre-kernel shift

---

Jenkinsfile
clients/benchmarks/CMakeLists.txt
clients/gtest/CMakeLists.txt

resolves centos and redhat build failures in gtest and benchmarks
Forces clang include to come before the conflicting system ones.
We need the OpenMP currently found in:
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include
but other includes conflict as too old.  Longer term solution still recommended.
E.g. include searching:
ignoring nonexistent directory "/opt/rocm/hcc/bin/../hcc/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/opt/rocm/hcc/bin/../include"
as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/opt/rocm/hcc/lib/clang/10.0.0/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/opt/rocm/hcc/lib/clang/10.0.0/include" …

fix centos/redhat include order

---

CMakeLists.txt
install.sh

When building rocBLAS with `install.sh --hip-clang`, it needs to default to code object V3 and set cmake variable Tensile_COMPILER to hipcc.

HIP Clang defaults to CO V3 & Tensile_COMPILER=hipcc

---

install.sh

When building rocBLAS with `install.sh --hip-clang`, code object version defaults to V3 and cmake variable Tensile_COMPILER sets to hipcc.  To do a full rocBLAS build with HIP Clang this way, Tensile commit 1e108edd2f113027c49e1b446674128569c4d425 is required for gfx908.  Since rocBLAS build still uses HCC by default, testing can be done with install.sh's -bdevelop option.  The changes to install.sh do not impact HCC build.

HIP Clang defaults to CO V3 & Tensile_COMPILER=hipcc (develop branch)

---

.githooks/pre-commit

`clang-format` does not, AFAIK, have options for removing trailing whitespace at the end of lines, or adding a missing newline at the end of a file.
The `emacs` `.dir-locals.el` file I added, automatically performs these edits upon saving a file, but for people who use `vim` or other editors, we need a consistent solution.
This changes the `pre-commit` script to run `sed` commands to strip trailing whitespace at the end of lines, and to add missing newlines at the end of files, on the same files for which `clang-format` is run.
There are also some simplifications of the `pre-commit` script, which previously used `/bin/sh` but for which `/bin/bash` adds more features.

Handle whitespace at the end of lines, and add newline at end of file if it doesn't exist

---

clients/benchmarks/CMakeLists.txt
clients/gtest/CMakeLists.txt
clients/samples/CMakeLists.txt

-  local includes forced before /opt/rocm/include by explicitly adding /opt/rocm/include as system include

SWDEV-205829-ignore-installed-rocblas

---

library/src/blas1/reduction_strided_batched.h
library/src/blas1/rocblas_asum.hpp
library/src/blas1/rocblas_asum_batched.hpp
library/src/blas1/rocblas_asum_strided_batched.hpp
library/src/blas1/rocblas_nrm2.hpp
library/src/blas1/rocblas_nrm2_batched.hpp
library/src/blas1/rocblas_nrm2_strided_batched.hpp

Remove an unnecessary template parameter in the reduction_strided_batched template.
This is a small PR, prior needed changes for merging asum/nrm2/iamax/iamin.
Other simplifications will follow in other PR (to keep PRs small).
-1  library/src/blas1/reduction_strided_batched.h
Remove the Ti parameter.
File where the use of the template is fixed:
-2  library/src/blas1/rocblas_asum.hpp
-3  library/src/blas1/rocblas_asum_batched.hpp
-4  library/src/blas1/rocblas_asum_strided_batched.hpp
-5  library/src/blas1/rocblas_nrm2.hpp
-6  library/src/blas1/rocblas_nrm2_batched.hpp
-7  library/src/blas1/rocblas_nrm2_strided_batched.hpp

Reduction template slight modification

---

library/src/blas1/reduction_strided_batched.h
library/src/blas1/rocblas_amax_amin.h
library/src/blas1/rocblas_asum.cpp
library/src/blas1/rocblas_asum.hpp
library/src/blas1/rocblas_asum_batched.cpp
library/src/blas1/rocblas_asum_batched.hpp
library/src/blas1/rocblas_asum_strided_batched.cpp
library/src/blas1/rocblas_asum_strided_batched.hpp
library/src/blas1/rocblas_nrm2.cpp
library/src/blas1/rocblas_nrm2.hpp
library/src/blas1/rocblas_nrm2_batched.cpp
library/src/blas1/rocblas_nrm2_batched.hpp
library/src/blas1/rocblas_nrm2_strided_batched.cpp
library/src/blas1/rocblas_nrm2_strided_batched.hpp
library/src/blas1/rocblas_reduction_impl.hpp
library/src/blas1/rocblas_reduction_template.hpp

and generalize its usage.
============================================
Generalize the 'template' and the 'impl' to be used by nrm2/asum/amax/amin
- 3/ NEW: library/src/blas1/rocblas_reduction_template.hpp
- 4/ NEW: library/src/blas1/rocblas_reduction_impl.hpp
============================================
- 5/ MODIFIED library/src/blas1/rocblas_asum.cpp
- 6/ MODIFIED library/src/blas1/rocblas_asum.hpp
- 7/ MODIFIED library/src/blas1/rocblas_asum_batched.cpp
- 8/ MODIFIED library/src/blas1/rocblas_asum_batched.hpp
- 9/ MODIFIED library/src/blas1/rocblas_asum_strided_batched.cpp
- 10/ MODIFIED library/src/blas1/rocblas_asum_strided_batched.hpp
============================================
- 11/ MODIFIED library/src/blas1/rocblas_nrm2.cpp
- 12/ MODIFIED …

introduce rocblas_reduction_template and rocblas_reduction_impl

---

clients/include/flops.hpp
clients/include/testing_dot.hpp
clients/include/testing_dot_batched.hpp
clients/include/testing_dot_strided_batched.hpp
clients/include/testing_scal.hpp
clients/include/testing_scal_batched.hpp
clients/include/testing_scal_strided_batched.hpp

Correcting complex flops calculations for L1 functions that do flops calculations:
- caxpy/zaxpy
- cdotu/zdotu & cdotc/zdotc
- scscal/dzscal & cscal/zscal
We should probably add flops calculations to all of the other functions some time in the future, and add them to logging.

Adding complex flops calcs. and updating other flop calcs.

---

clients/gtest/blas1_gtest.yaml
clients/include/testing_dot_batched.hpp
clients/include/testing_dot_strided_batched.hpp

Looks like batched/strided_batched dot tests were removed accidentally in 4589ef5e403e6fa9657277a649603b4d5d809e48.
Added back these tests. dot(c)_batched and dot(c)_strided_batched tests are failing on the host. They seem to only fail with smaller N sizes (they passed the initial PR with N ~= 33000) and batch_count > ~16 or so. Will create a ticket for this bug; I don't have time to look into it right now, hopefully someone else does. Commented out host-side tests for now.

Added back dot tests, commented out failing dot host tests.

---

docker/dockerfile-build-sles

It looks like that zypper update is causing dependent system packages like systemd to be installed, which require a reboot, which isn't possible in a container. This results in the docker stage returning an error code. Other projects are not calling zypper update and thus do not error out when trying to install packages.

Trying to fix sles errors

---

clients/include/rocblas_test.hpp

Add `virtual` and `final` specifiers to some functions in `rocblas_test.hpp` to enforce class usage expectations, such as not overriding `operator bool()` in derived classes.
(This would detect and flag the TRMM case where `operator bool()` was still being overridden, even though it wasn't necessary anymore.)

Add final specifiers to enforce expectations about rocBLAS test class usage

---

clients/include/device_vector.hpp
clients/include/testing_dot_batched.hpp
clients/include/testing_dot_strided_batched.hpp

The `rocblas_error_*` were uninitialized.
The initializer lists were not in the same order as the bases/members they initialized.

Fix uninitialized variables and order of initializer lists

---

.githooks/pre-commit
CMakeLists.txt
LICENSE.md

Simplify the pattern used to find files to reformat in `pre-commit`, making use of only one instance of `\.in$` instead of `\.cpp\.in$`, `\.hpp\.in$`, etc, since in this part of the script we're only removing whitespace at the end of lines and filling a missing newline at EOF (`clang-format` is done later with a different pattern).
Add `\.pl$` pattern for Perl scripts, and remove the Unicode copyright character from LICENSE.md, since it doesn't appear in any other files, and it makes the copyright dates harder to parse. This change also allows the `pre-commit` script to automatically adjust the copyright date range for `LICENSE.md`.

Change pre-commit script and LICENSE.md to allow parsing of copyright dates

---

library/src/blas_ex/rocblas_gemm_ex.hpp

Fixes SWDEV-210362.
- Avoid unnecessary hipMemCpys for strided_batched/batched versions of gemm_ex
- Remove change causing #batch_count calls to Tensile rather than a single strided_batched call for gemm_strided_batched_ex
These issues were introduced in d300cc1c3ecac1dae352829142851425b4849b9e and solved later in b87c84d6db25f123af8be38c7f48826db1be4298 where batched scalars were removed. This PR is a quick fix for removing batched scalars.

Fix for SWDEV-210362

---

docker/dockerfile-build-centos
docker/dockerfile-build-sles

This PR might solve rocSOLVER's CI failure, as it is picking up an old version of gtest when it installs rocblas from CI

Remove source gtest and unnecessary dependencies from dockerfile

---

CMakeLists.txt
Jenkinsfile
install.sh

Fix for SWDEV-212579 and blis based testing on other CPUs by making blis configuration generic.
For 3.0 release branch integration.

blis generic

---

install.sh

* allow faster test build and package with no tensile and no client, use "-n" flag by itself

move tensile options to common options

---

library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/archive/vega20_Cijk_Alik_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_ci/vega20_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_ci/vega20_Cijk_Alik_Bljk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Ailk_Bjlk_HB.yaml
library/src/blas3/Tensile/Logic/asm_full/vega20_Cijk_Alik_Bljk_HB.yaml

- the following sizes are specifically tuned
```
hgemm TN m 1024 n 8192 k 4097, 16993 GFlops (previously 15938 GFlops)
hgemm NT m 1024 n 1024 k 8192, 18497 GFlops (previously 15676 GFlops)
```
Checklist:
- Tensile-generated & merged logic yaml in `archive/`
- Massaged logic yaml in `asm_ci/` & `asm_full/`

Update non-batched hgemm logic yaml

---

library/src/blas_ex/rocblas_gemm_ex.hpp

resolves #SWDEV-213985
At this if statement, a normal trsm call would end up in the if section where no copies are done, instead now we are getting to the else portion. This is happening because stride_c is now explicitly being set to 0 (Actually Trsm’s stride_b when calling the template). Because the batch count is 1 the actual value for stride does not matter.
Previously we were setting this gemm_ex stride c to the supposedly correct size even though batch_count is 1. (Within rocblas_gemm_ex_impl)
Creating PR to run tests - Still testing regression

fixing gemm_ex logic to avoid copies

---

library/src/blas1/rocblas_copy.cpp
library/src/blas1/rocblas_copy.hpp
library/src/blas1/rocblas_copy_batched.cpp
library/src/blas1/rocblas_copy_strided_batched.cpp
library/src/blas2/rocblas_tbmv.hpp
library/src/blas3/rocblas_trmm.hpp

Removing  a useless template parameter in rocblas_copy_template

Removing unnecessary template parameter in rocblas_copy_template

---

library/CMakeLists.txt

ROCm3.0 is changing package names to conform with debian naming conventions. As hip_hcc is being renamed, the dependency is now changed to rocm-dev. rocm-dev is meta package's name will be unchanged in ROCm3.0

Package Dependency is changed to rocm-dev metapackage

---

docs/source/install.rst

Currently there doesn't seem to be any documentation on system memory requirements to build rocBLAS. This PR may not be 100% accurate so discussion is welcome on what the requirements _actually_ are.
Andrew mentioned that he was able to successfully build on a Vega20 with 24GB.

Adding system requirements to install documentation

---

clients/benchmarks/client.cpp
clients/common/rocblas_gentest.py
clients/gtest/CMakeLists.txt
clients/gtest/rocblas_gtest.yaml
clients/gtest/trmv_gtest.cpp
clients/gtest/trmv_gtest.yaml
clients/include/cblas_interface.hpp
clients/include/flops.hpp
clients/include/rocblas.hpp
clients/include/rocblas_template.yaml
clients/include/testing_logging.hpp
clients/include/testing_trmv.hpp
clients/include/testing_trmv_batched.hpp
clients/include/testing_trmv_strided_batched.hpp
library/include/rocblas-functions.h
library/src/CMakeLists.txt
library/src/blas2/rocblas_trmv.cpp
library/src/blas2/rocblas_trmv.hpp
library/src/blas2/rocblas_trmv_batched.cpp
library/src/blas2/rocblas_trmv_batched.hpp
library/src/blas2/rocblas_trmv_strided_batched.cpp
library/src/blas2/rocblas_trmv_strided_batched.hpp
library/src/blas2/trmv_device.hpp
library/src/blas2/trmv_template.hpp

SWDEV-211980
CLIENT SIDE /////////////////
-1/ modified:   clients/benchmarks/client.cpp
adding trmv headers and add references to trmv routines
-2/ modified:   clients/common/rocblas_gentest.py
adding default values of strides for the trmv strided batched routine
-3 /  modified:   clients/gtest/CMakeLists.txt
Reference the trmv_gtest.yaml file
-4 / modified:   clients/gtest/rocblas_gtest.yaml
Include the rocblas_trmv.yaml file
-5/  modified:   clients/include/cblas_interface.hpp
Add complex types for the cblas trmv routine.
-6 /  modified:   clients/include/flops.hpp
Add flop counts for the non-batched trmv routine.
-7/  modified:   clients/include/rocblas.hpp
add headers of the trmv routines.
-8 / modified:   clients/include/rocblas_template.yaml
Add trmv routines
-9/ modified: …

BLAS level 2 trmv routines (non batched, batched, strided batched)

---

library/include/rocblas-types.h
library/src/rocblas_auxiliary.cpp

E.g. usage:
* rocblas_status_invalid_value for unsupported parameter enum values
* rocblas_status_continue for the passing of intermediate checks

adds status enums

---

install.sh
library/CMakeLists.txt

Switch to using rocm-dev instead of hip_hcc package dependency.

Replace hip_hcc with rocm-dev for HIP-Clang VDI

---

install.sh
library/CMakeLists.txt

2.10-hipclang requires dependency on rocm-dev instead of hip_hcc.

[2.10-hipclang] replace hip_hcc with rocm-dev

---

library/src/CMakeLists.txt

* The linker rpath will be set only if ROCM_RPATH is defined in the ENV
* Match the patching of master patch branches

Adding RUNPATH to rocBLAS lib (#852)

---

library/include/rocblas-types.h

May need to be cherry-picked and applied to master, to fix SWDEV-216454

Fix Usage of _Float16 to clang 9 or later

---

library/include/rocblas-types.h

cherry-pick Lee's fix for clang version detection

Fix Usage of _Float16 to clang 9 or later (#878)

---

install.sh
library/src/CMakeLists.txt

Same change as hip-clang branch; this needs to be a universal setting

Do not run header compilation tests under hip-clang

---

install.sh
library/CMakeLists.txt

Old hip_hcc and rocm_smi64 packages will cause the installation to fail on rocm 3.0. Replacing with rocm-dev should fix this issue.

Remove hip_hcc dependencies and replace with rocm-dev

---

docker/dockerfile-build-ubuntu

resolves CI failures in Ubuntu

Changing docker name for new smi library

---

library/include/rocblas-complex-types.h

Fix complex `abs()` to return `0` instead of `NaN` when both the real and imaginary parts are 0.

Fix abs(0,0) to return 0 instead of NaN

---

install.sh

Installing rocm-dev causing the run time environment to change from hip-vdi to hip-hcc

Disable rocm-dev when building with hip-clang

---

Jenkinsfile
clients/benchmarks/CMakeLists.txt
clients/gtest/CMakeLists.txt
clients/samples/CMakeLists.txt
docker/dockerfile-build-centos
docker/dockerfile-build-ubuntu-rock
install.sh
library/CMakeLists.txt

With the changes in this PR, rocblas can be built using the hip-clang compiler on CentOS. I'll merge it after it passes CI.

Fix CentOS compilation errors for hip-clang

---

.jenkins/Extended_TOT_Tensile.groovy
.jenkins/PreCheckin_TOT_Tensile.groovy
CMakeLists.txt
install.sh

This PR adds a flag that allows the user to install an older version of Tensile without the install script returning an error code. Mostly, this is for CI purposes.

Add flag to ignore Tensile version

---

CMakeLists.txt
install.sh
library/src/CMakeLists.txt

Will enable the tensile new client by default
added -r / --no-tensile-host option to install.sh to build with old client.
Fixed a bug which prevented the packaging of the tensile library for getting installed.

Make new Tensile client the default

---

clients/gtest/hpr_gtest.yaml

I think the failing tests are from memory allocation failures. Reducing the size of stride_scale for large hpr tests, will wait to see if this passes CI.

Removing large stride_scale for large hpr tests.

---

clients/gtest/spr2_gtest.yaml
clients/gtest/spr_gtest.yaml

Just like hpr failed previously, some test cases for spr2 are too large for CI. Not sure how this wasn't caught by CI earlier.

Reducing size of large test cases for spr2 and spr.

---

clients/CMakeLists.txt

Temporary change to permit use of rocblas-bench. Remove when AOCL BLIS packaging is implemented

Add BLIS .so files to client package

---

library/src/blas3/Tensile/Logic/asm_full/arcturus_Cijk_Ailk_Bjlk_SB.yaml
library/src/blas3/Tensile/Logic/asm_full/arcturus_Cijk_Alik_Bljk_SB.yaml

Vega 20 ISA values were present in arcturus SB logic files.  Corrected.

correct bogus ISA values in arcturus SB logic files

---

install.sh

- llvm7 is a mandatory library dependency for the new Tensile client. This PR adds it to the install script for sles and fedora

Added llvm7 dependency for sles

---

library/src/CMakeLists.txt
library/src/include/handle.h

allow limited warnings to apply to library build not clients or anything outside

restrict warnings to library

---

library/include/rocblas-types.h

This reverts commit 24c189f941fad4692cf6a5ef8b299c2d90f232fd.
Looks like this commit breaks rocBLAS, so this should be removed.

Revert "Avoid using Float16 type if using llvm clang++ (#1000)"

---

clients/gtest/trsm_gtest.yaml

[SWDEV-208995](http://ontrack-internal.amd.com/browse/SWDEV-208995).
Moves a test from nightly to pre-checkin, I'm guessing to check for lda/ldb edge case. @leekillough please let me know if this is what was intended from the ticket or not because it wasn't 100% clear to me.

SWDEV-208995

---

library/src/tensile_host.cpp

change in tensile host initialization to only load modules for the current architecture.

update tensile init to only load valid modules

---

clients/common/rocblas_gentest.py
clients/gtest/gemm_batched_gtest.yaml
clients/gtest/gemm_gtest.yaml
clients/gtest/gemm_strided_batched_gtest.yaml
library/src/tensile_host.cpp

Resolves SWDEV-223351
When `K == 0`, rocBLAS will set `K == 1` and `alpha == 0`, because Tensile does not support 0-sized dimensions right now.
Add `K == 0` tests, since they weren't being tested.
Change the computation of default `LDA` and `LDB` to use `1` if `K == 0`, because `0` is not a valid leading dimension.

Support and test K==0 in GEMM

---

library/src/tensile_host.cpp

Fixes SWDEV-224021, SWDEV-223629
Full rocblas-test passed in docker 1901-MIOpen2.2.x-92186831-py3-ub16.04-3.1.20066-f2ab87d-hip-stg-job730

update tensile init to only load valid modules (#1012)

---

.jenkins/debug.groovy
.jenkins/extended.groovy
.jenkins/precheckin.groovy
clients/common/utility.cpp
clients/gtest/rocblas_gtest_main.cpp
clients/include/d_vector.hpp
clients/include/device_batch_vector.hpp
clients/include/device_strided_batch_vector.hpp
clients/include/device_vector.hpp
clients/include/rocblas_test.hpp
clients/include/testing_gemm.hpp
clients/include/testing_gemm_ex.hpp
clients/include/testing_ger.hpp
clients/include/testing_ger_batched.hpp
clients/include/testing_ger_strided_batched.hpp
clients/include/testing_set_get_matrix_async.hpp
clients/include/testing_syr_batched.hpp
clients/include/utility.hpp

Potentially resolves [SWDEV-223558](http://ontrack-internal.amd.com/browse/SWDEV-223558) and [SWDEV-220984](http://ontrack-internal.amd.com/browse/SWDEV-220984).
Summary
------------
This allows tests to check how much memory will be allocated on the device, and compares this to how much memory is free. If the amount of memory to be allocated is greater, it immediately succeeds, and allows logging that a test was skipped.
This seems a little hacky, so any advice is appreciated.
Implementation
--------------------
In utility.cpp, I use `hipMemGetInfo` to query how much memory is available. In each test, I calculate how much memory is needed, and if it's  greater, I use googletest's SUCCESS with a unique message. In rocblas_gtest_main.cpp the listener detects this message and records the …

Not running tests when more memory is needed than available.

---

clients/gtest/rocblas_gtest_main.cpp
clients/include/utility.hpp

Fix for commit 5a3b4689233375618e453b2b92238a1081a1c0f4.
The previous commit would print that tests were skipped for any failed tests due to an incorrect use of strcmp. This should be fixed here.

Fix skipping tests

---

clients/benchmarks/client.cpp
clients/include/rocblas_arguments.hpp
clients/include/rocblas_common.yaml
clients/include/testing_gemm.hpp
clients/include/testing_gemm_batched.hpp
clients/include/testing_gemm_batched_ex.hpp
clients/include/testing_gemm_ex.hpp
clients/include/testing_gemm_strided_batched.hpp
clients/include/testing_gemm_strided_batched_ex.hpp

add parameter to the rocblas-bench to set the number of cold calls used for bench marking. 
this feature is enabled for the gemm tests.

add command line option of setting cold calls

---

install.sh

Resets the install.sh to build with the new tensile client to false so by default we build with the old client.
The pre_checkin tests passed locally on a vega20 machine.

revert to build with old tensile client

---

clients/include/rocblas_arguments.hpp
library/src/include/logging.h

Make Google tests print types as symbolic names instead of numbers.
This is a short-term fix.
PR #922 will incorporate this into its system, where all formatted IO is done in one place instead of scattered around.

Make Google Tests print type symbolically instead of numerically

---

clients/gtest/rocblas_gtest_main.cpp
library/include/rocblas-functions.h
library/src/rocblas_auxiliary.cpp

Add `rocblas_init` function to initialize rocBLAS structures (such as new Tensile client), to avoid first-time overhead.
(Note: Some of the changes are untabification or removal of trailing spaces.)

Add rocblas_init

---

clients/include/rocblas_init.hpp
clients/include/testing_copy_batched.hpp
clients/include/testing_dot.hpp
clients/include/testing_dot_batched.hpp
clients/include/testing_dot_strided_batched.hpp
clients/include/testing_gemm_batched.hpp
clients/include/testing_gemv_batched.hpp
clients/include/testing_ger_batched.hpp
clients/include/testing_nrm2_batched.hpp
clients/include/testing_rot_batched.hpp
clients/include/testing_rotg_batched.hpp
clients/include/testing_rotm_batched.hpp
clients/include/testing_rotmg_batched.hpp
clients/include/testing_sbmv_batched.hpp
clients/include/testing_scal_batched.hpp
clients/include/testing_spmv_batched.hpp
clients/include/testing_swap_batched.hpp
clients/include/testing_symv_batched.hpp
clients/include/testing_syr_batched.hpp
clients/include/testing_trsm_batched.hpp
clients/include/testing_trsm_batched_ex.hpp
clients/include/testing_trsv_batched.hpp
clients/include/testing_trtri_batched.hpp

Updating *_batched tests to use `device_batch_vector<T>` rather than `device_vector<T*,0,T>`, along with `CHECK_DEVICE_ALLOCATION` rather than `CHECK_HIP_ERROR` for device memory allocation.
I will make another PR to update *_strided_batched tests to use `CHECK_DEVICE_ALLOCATION` in the near future.

Update *_batched tests

---

install.sh

Cherry pick of PR #1040. Had to fix merge conflict, so it doesn't appear as a cherry-pick. This needs to be in the master-rocm-3.2 branch as the point release packages will be available starting in rocm 3.2

Add flag to install version-specific rocm-dev

---

clients/include/rocblas_test.hpp

From @zaliu:
For nightly, I got through the tests on this puny 8GB VRAM Vega 10, with only 2 skipped:
```
[----------] Global test environment tear-down
[==========] 514269 tests from 140 test cases ran. (27237522 ms total)
[  PASSED  ] 514269 tests.
[ SKIPPED  ] 2 tests.
rocBLAS version: 2.17.0.1990-4b4fbc51
```
Nice job!

Skip tests when cannot allocate enough memory.

---

clients/benchmarks/CMakeLists.txt
clients/gtest/CMakeLists.txt
clients/samples/CMakeLists.txt

hip::device is supported by both hip_hcc and hip_vdi, so switching to this new cmake target should fix issues on HIP-Clang CI when building tests.
https://github.com/ROCm-Developer-Tools/HIP/blob/master/CMakeLists.txt#L351

Change CMake target hip::hip_hcc to hip::device

---

clients/gtest/rocblas_gtest_main.cpp

Separate `rocblas-test` `main()` into separate functions, to make `main()` more readable, and to print the version information in one function rather than in two places in `main()` (it also prints "new Tensile client" or not).

Cleanup rocblas_gtest_main.cpp

---

clients/include/d_vector.hpp
clients/include/device_batch_vector.hpp
clients/include/device_strided_batch_vector.hpp
clients/include/device_vector.hpp
clients/include/rocblas_test.hpp

- Removes the use of `hipMemGetInfo()` introduced in #1011 to query available device memory before allocation. This has been proven to be an unreliable way of getting available memory on the device. We shouldn't need this query since we're skipping tests on failed memory allocation as well.

Remove pre-check for memory allocation.

---

install.sh

The end goal for these CentOS6-related mods is to support a manylinux2010 build environment on ROCm.
On CentOS-6, the llvm7.0-* packages do not exist.  In order to install a modern version of LLVM on CentOS-6, it must be built from source.  Hence, this PR's purpose is to remove the llvm7.0-* packages from the dependency list for versions of CentOS that are less than 7.  
Additionally, CentOS-6 doesn't include a '/etc/os-release' file, so we grab the details from the '/etc/centos-release' file instead (if it exists).

Enable support on CentOS-6

---

library/src/blas2/rocblas_tpsv.hpp

- This is already in the master and the hipclang-bkc3 branches, just adding this to develop

Add missing __device__ label (#1049)

---

clients/gtest/gbmv_gtest.cpp
clients/gtest/gbmv_gtest.yaml
clients/include/testing_gbmv.hpp
clients/include/testing_gbmv_batched.hpp
clients/include/testing_gbmv_strided_batched.hpp
library/src/blas2/rocblas_gbmv.cpp

See [LWPMLSE-37](http://ontrack-internal.amd.com/browse/LWPMLSE-37).
A proposal for moving quick-return and invalid_size checks into their own function to reduce the explosion of repeated test cases.
This takes any useful quick return and invalid_size combinations and moves them to their own `testing_xxx_arg_check` function and out of the regular quick tests.
For example, this will remove testing all `incx`/`incy` and `alpha`/`beta` combinations when `M == -1`.
This draft only implements this for gbmv to help discussion. If everyone likes this I can move ahead with other functions.
Previously quick gbmv tests (not batched nor strided_batched) ran 10368 tests in around 15.8s. With this change quick gbmv tests run 5618 tests in around 10.8s. A 5s (or ~33%) improvement but will add up across …

Move quick-return and invalid-size into own function

---

library/src/blas2/rocblas_sbmv.hpp
library/src/blas2/rocblas_spmv.hpp
library/src/blas2/rocblas_symv.hpp

Noticed that a hip-clang build was broken in CI ([here](http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang-int-bkc-3%2Fprecheckin%2FrocBLAS/detail/develop/15/pipeline/74)) this should fix it.

hipclang fixes.

---

library/include/rocblas_bfloat16.h

Downgrades `rocblas_bfloat16.h` to C++11 code instead of C++14 code.
Right now `rocblas_bfloat16.h` uses either C++14 code, or layout-compatible C89 code, depending on the compiler.
This changes it to use either C++11 code, or layout-compatible C89 code, so that C++11 compilers can enjoy the benefits of it, even though rocBLAS itself requires C++14 to compile.
(This is a _public_ rocBLAS header file, and so it needs to support more different build environments than the C++14 that the rocBLAS internal code requires. The `header_compilation_tests.sh` script ensures that it compiles correctly with C89, C++11 and C++14.)

Downgrade rocblas_bfloat16.h to C++11

---

clients/gtest/tbmv_gtest.yaml
clients/include/testing_tbmv.hpp
clients/include/testing_tbmv_batched.hpp
clients/include/testing_tbmv_strided_batched.hpp
library/src/blas2/rocblas_tbmv.cpp
library/src/blas2/rocblas_tbmv_batched.cpp
library/src/blas2/rocblas_tbmv_strided_batched.cpp

I noticed while going through to reduce tests that tbmv didn't have any tests for N > lda > k, which is a valid use case. The tests were broken for this case, so I added tests and fixed the testing suite for this.
Will be reducing the number of tests here in a future commit (along with many other functions).

FIxing tbmv testing.

---

clients/include/testing_tbsv.hpp
clients/include/testing_tbsv_batched.hpp
clients/include/testing_tbsv_strided_batched.hpp
clients/include/testing_tpsv_batched.hpp
clients/include/testing_tpsv_strided_batched.hpp
clients/include/testing_trsv.hpp
clients/include/testing_trsv_batched.hpp
clients/include/testing_trsv_strided_batched.hpp
library/src/blas2/rocblas_tbsv_batched.cpp
library/src/blas2/rocblas_tbsv_strided_batched.cpp
library/src/blas2/rocblas_tpsv_batched.cpp
library/src/blas2/rocblas_tpsv_strided_batched.cpp
library/src/blas2/rocblas_trsv.cpp
library/src/blas2/rocblas_trsv_batched.cpp
library/src/blas2/rocblas_trsv_strided_batched.cpp

Changing the order of checks for tbsv, trsv, and tpsv.
Previously, if batch_count == 0 we did not return invalid_size for bad input args (such as M < 0). This is being changed here to match the rest of the library (i.e. do invalid_size checks first, then do quick return checks after, including batch == 0 checks).
Still waiting to build on my machine to test trsv changes.

Changing order of checks for L2 solvers.

---

library/include/rocblas-types.h

- This is due to clang++ 9.0.0 incompatibility, which causes problems for hipBLAS.
- Will need to propagated to master as well

Use _Float16 only if clang >= 10 

---

.github/CONTRIBUTING.md
docs/source/contributing.rst
library/src/CMakeLists.txt

The `build` directory should be used to store files generated automatically during builds, rather than the source directory.
Also, rocBLAS files should not go into the `library/include` directory unless they are **public C-compatible** header files which are documented and supported. This does not apply to internal C++ headers.
This PR:
1. Keeps the source directory clean (`git status`) after builds, without requiring `.gitignore`.
2. Preserves the invariant that `library/include` consists only of C-compatible public header files.
3. Documents these best practices in `CONTRIBUTING.md` and `contributing.rst`.
4. Is in keeping with the CMake philosophy that a build directory is self-contained, and if the `cmake` command is run from a build _working directory_, then all of the files …

Use build directory instead of source directory for generated files

---

clients/include/rocblas_test.hpp
clients/include/utility.hpp

This fixes an undefined macro for `CHECK_HIP_ERROR`, fixes poisoned identifiers by `#include`ing `gtest/gtest.h` first, and puts the `hipMalloc/hipFree` code next to the poisoned identifiers `#ifdef` test.

Cleanup macros and #include file ordering

---

clients/gtest/CMakeLists.txt
clients/gtest/rocblas_gtest_main.cpp
clients/gtest/rocblas_test.cpp
clients/include/rocblas_test.hpp
clients/include/testing_gemm_batched_ex.hpp
clients/include/testing_gemm_strided_batched_ex.hpp
clients/include/testing_trsm_batched.hpp
clients/include/testing_trsm_batched_ex.hpp
clients/include/testing_trsm_strided_batched.hpp
clients/include/testing_trsm_strided_batched_ex.hpp
clients/include/utility.hpp
library/include/rocblas-functions.h
library/src/handle.cpp
library/src/include/rocblas_ostream.hpp
library/src/rocblas_ostream.cpp
library/src/tensile_host.cpp

Adds a 10-minute alarm for every test case (the maximum right now is around 2 minutes on GFX906). If a test takes more than 10 minutes, then all testing is aborted, and a message explaining why is displayed. This should prevent the hangs in the CI when an aborted test is recovered from and everything hangs afterwards, probably because of a deadlock from a still-locked mutex.
Make `catch_signals_and_exceptions_as_failures` nestable, and put it around rocBLAS calls as close as possible, to reduce memory leaks. If a signal occurs in a rocBLAS call, it will be caught and translated into a Google Test failure, but the surrounding vector allocations will still be able to be destructed.
Clean up the implementation to use strict standard-conforming `sigsetjmp` usage, and catch `std::terminate`. …

Add alarm to tests to detect hangs; reduce memory leaks in tests; improve rocblas_abort implementation; make sigsetjmp code conformant; add comments

---

.github/CONTRIBUTING.md
docs/cleanup_text.sh
docs/source/contributing.rst

Add another guideline for macros (motivated by a recent bug caused by a macro expansion's local variable `status` conflicting with a macro caller's `status` without any compile-time error, just a strange runtime failure), and enhance `cleanup_text.sh` to handle quoted code segments in restructuredtext with a language specified.

Improve docs

---

clients/include/norm.hpp
clients/include/rocblas_init.hpp
clients/include/testing_asum_batched.hpp
clients/include/testing_axpy_batched.hpp
clients/include/testing_gbmv_batched.hpp
clients/include/testing_gemm_batched.hpp
clients/include/testing_gemm_batched_ex.hpp
clients/include/testing_hbmv_batched.hpp
clients/include/testing_hemv_batched.hpp
clients/include/testing_her2_batched.hpp
clients/include/testing_her_batched.hpp
clients/include/testing_herk_batched.hpp
clients/include/testing_herk_strided_batched.hpp
clients/include/testing_hpmv_batched.hpp
clients/include/testing_hpr2_batched.hpp
clients/include/testing_hpr_batched.hpp
clients/include/testing_hpr_strided_batched.hpp
clients/include/testing_reduction_batched.hpp
clients/include/testing_rotmg_batched.hpp
clients/include/testing_spmv_batched.hpp
clients/include/testing_spr2_batched.hpp
clients/include/testing_spr_batched.hpp
clients/include/testing_syrk_batched.hpp
clients/include/testing_syrk_strided_batched.hpp
clients/include/testing_tbmv_batched.hpp
clients/include/testing_tpmv_batched.hpp
clients/include/testing_trmv_batched.hpp

Should resolve [SWDEV-220984](http://ontrack-internal.amd.com/browse/SWDEV-220984). Apparently I missed updating a bunch of batched tests to the new memory checking scheme. This should use `CHECK_DEVICE_ALLOCATION` instead of `CHECK_HIP_ERROR` when calling `memcheck` on all device vectors now.
Also updates gemm_batched_ex test to use new batch_vectors as these tests were segfaulting apparently.

Batched memcheck fixes

---

clients/benchmarks/client.cpp
library/src/rocblas_ostream.cpp

Only use exact FP precision for YAML output; use std::setprecision in rocblas-bench

---

clients/benchmarks/client.cpp
clients/common/utility.cpp
clients/gtest/rocblas_gtest_main.cpp
library/include/rocblas-functions.h
library/src/rocblas_auxiliary.cpp

Renames `rocblas_init` to `rocblas_initialize`.
Changes `rocblas-bench` timing functions to use `clock_gettime` instead of `gettimeofday`.
Calls `rocblas_initialize` _before_ Boost `parse_command_line()`. This causes 5-10 seconds of initialization time before the command returns, even if it can return immediately, like `rocblas-bench --help`. It is uncertain why initialization of rocBLAS has to occur before running Boost `parse_command_line()` in order to get good performance results.

Rocblas initialize

---

clients/include/testing_logging.hpp
library/src/handle.cpp
library/src/include/handle.h

This makes the logging handle-specific, which, by rocBLAS rules, is thread-specific. It initializes the handle's logging during handle creation, and uses the `ROCBLAS_LAYER` environment variable's value at the time of handle creation, to determine the logging for that handle. It removes the legacy code which made logging a static member of `rocblas_handle`.
The recent change #922 had mostly to do with making the IO thread-safe in the sense of not interleaving output from multiple threads writing to the same file/device, while remaining as lock-free as possible. This change, and #1129 _make the actual data structures thread-local_, **which is an orthogonal and much simpler issue** than #922.

Make logging handle-specific

---

library/src/CMakeLists.txt

* hides llvm symbols used by embedded rocblas-tensile library

SWDEV-246520-hide-symbols

---

CMakeLists.txt

Fixes:
```
CMake Error at CMakeLists.txt:180 (set_property):
set_property could not find CACHE variable Tensile_LIBRARY_FORMAT.  Perhaps
it has not yet been created.
```

Define the Tensile_LIBRARY_FORMAT variable

---

clients/include/blas2/testing_syr_strided_batched.hpp
clients/include/blas3/testing_gemm_strided_batched.hpp
clients/include/blas_ex/testing_rot_strided_batched_ex.hpp

- resolves SWDEV-280617
- The function ArgumentModel divides gpu_time by number_hot_calls so the calling code should not do this division.
- This fix is for the three functions: syr_strided_batched, gemm_strided_batched, rot_strided_batched

remove division by number_hot_calls when using ArgumentModel

---

CHANGELOG.md

- This PR is to rocBLAS:release/rocm-rel-5.0. It will be merged back into rocBLAS-internal:develop in a future PR

update CHANGELOG.md for ROCm 5.0.0

---

library/src/CMakeLists.txt

resolves #___
- Original Header File Dump enabled for version header file wrapper to support backward Compatibility for PT/TF
- Depends on wrapper functions of rocm-cmake version https://github.com/RadeonOpenCompute/rocm-cmake/commit/d108dbf05e029996d5d7bcbe258abb1166547a30

ENABLE ORIGINAL FILE DUMP IN VERSION HDR FILE WRAPPER FOR BKWDCOMP

---

library/src/handle.cpp
library/src/include/handle.hpp

Hotfix to hide hipMallocAsync/hipFreeAsync on ROCm 5.2 and earlier.

Hotfix to hide hipMallocAsync/hipFreeAsync on ROCm 5.2 and earlier.

---

library/src/blas3/Tensile/Logic/asm_full/aldebaran/aldebaran_Cijk_Ailk_Bljk_HHS_BH.yaml
library/src/blas3/Tensile/Logic/asm_full/aldebaran/fp16altimpl/aldebaran_Cijk_Ailk_Bljk_HHS_BHR.yaml
library/src/blas3/Tensile/Logic/asm_full/aldebaran_104cu/aldebaran_Cijk_Ailk_Bljk_HHS_BH.yaml
library/src/blas3/Tensile/Logic/asm_full/aldebaran_104cu/fp16altimpl/aldebaran_Cijk_Ailk_Bljk_HHS_BHR.yaml
library/src/blas3/Tensile/Logic/asm_full/arcturus/arcturus_Cijk_Ailk_Bljk_HHS_BH.yaml

@AlexBrownAMD please double check that the updates look correct. Git merge handled them all automatically except for aldebaran/fp16altimpl, which I did manually.

cherry-pick Replace kernel with a memory error (#1484)

---

clients/benchmarks/client.cpp
clients/common/utility.cpp
clients/gtest/multiheaded_gtest.cpp
clients/include/utility.hpp
clients/samples/CMakeLists.txt
library/src/tensile_host.cpp

resolves SWDEV-386410
- Refactor initialization time reporting for clarity
- Skip experimental code objects in rocblas_initialize
- Output only maximum memory per device

Hotfix for rocblas initialization time issues

---

library/include/internal/rocblas-types.h
library/include/rocblas_module.f90
library/src/CMakeLists.txt
library/src/blas_ex/rocblas_gemm_batched_ex.cpp
library/src/blas_ex/rocblas_gemm_ex.cpp
library/src/blas_ex/rocblas_gemm_strided_batched_ex.cpp
library/src/blas_ex/rocblas_trsv_batched_ex.cpp
library/src/blas_ex/rocblas_trsv_ex.cpp
library/src/blas_ex/rocblas_trsv_strided_batched_ex.cpp
library/src/rocblas_auxiliary.cpp

cherry-pick https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/commit/9eacbb249f64aaef0bf789c2ccad4336d9234295 and https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/commit/06b51585aef2356e2bc3cc6ffc13d41f3b8555d7 and merge conflict fixes into 5.7.

Add missing symbols for hipblas with no-tensile build
